wavesplatform/matcher

dex/dex-devnet.conf
dex/dex-mainnet.conf
dex/dex-testnet.conf
dex/src/main/resources/application.conf
dex/src/main/scala/com/wavesplatform/dex/Matcher.scala
dex/src/main/scala/com/wavesplatform/dex/WatchDistributedCompletionActor.scala
dex/src/main/scala/com/wavesplatform/dex/market/MatcherActor.scala
dex/src/main/scala/com/wavesplatform/dex/settings/MatcherSettings.scala
dex/src/main/scala/com/wavesplatform/dex/util/ActorNameParser.scala
dex/src/test/scala/com/wavesplatform/dex/WatchDistributedCompletionActorSpecification.scala
dex/src/test/scala/com/wavesplatform/dex/settings/MatcherSettingsSpecification.scala

* Added internal MatcherSettings.process-consumed-timeout;
* WatchDistributedCompletionActor schedules a timeout, also it works correctly if there is no worker. Added unit tests;
* Examples of configurations contains a line to enable DEX;

DEX-330 Timeout after an order book deletion

---

dex/src/main/resources/application.conf
dex/src/main/scala/com/wavesplatform/dex/Matcher.scala
dex/src/main/scala/com/wavesplatform/dex/api/MatcherApiRoute.scala
dex/src/main/scala/com/wavesplatform/dex/error/MatcherError.scala
dex/src/main/scala/com/wavesplatform/dex/history/HistoryRouter.scala
dex/src/main/scala/com/wavesplatform/dex/market/ExchangeTransactionBroadcastActor.scala
dex/src/main/scala/com/wavesplatform/dex/market/OrderBookActor.scala
dex/src/main/scala/com/wavesplatform/dex/model/MatcherModel.scala
dex/src/main/scala/com/wavesplatform/dex/model/OrderBook.scala
dex/src/main/scala/com/wavesplatform/dex/settings/MatchingRules.scala
dex/src/main/scala/com/wavesplatform/dex/settings/OrderRestrictionsSettings.scala
dex/src/main/scala/com/wavesplatform/dex/settings/package.scala
dex/src/test/scala/com/wavesplatform/dex/api/MatcherApiRouteSpec.scala
dex/src/test/scala/com/wavesplatform/dex/market/MatcherActorSpecification.scala
dex/src/test/scala/com/wavesplatform/dex/market/OrderBookActorSpecification.scala
dex/src/test/scala/com/wavesplatform/dex/model/MatchingRulesSpecification.scala
dex/src/test/scala/com/wavesplatform/dex/model/OrderBookSpec.scala
dex/src/test/scala/com/wavesplatform/dex/model/RawMatchingRulesSpecification.scala
dex/src/test/scala/com/wavesplatform/dex/settings/MatcherSettingsSpecification.scala

REST API:
* GET /orderbook/{amountAsset}/{priceAsset}/info returns "restrictions" (an old fields) and "matchingRules.tickSize";
* GET /orderbook returns matchingRules;
Internal:
* OrderBookActor updates the current matching rules during the rules switch;
* Removed RawMatchingRules.mergePrices, because "disabled" option means the most minimal tick size for this order book;
* RawMatchingRules.rawMatchingRulesNelReader doesn't prepend the default rules, because we don't know asset's decimals during config parsing. They are prepended in the Matcher;
* Added OrderRestrictionsSettings.Default;
* TickSize is removed;
* OrderBook works with normalizedTickSize: Long instead of tickSize: TickSize;
* ExchangeTransactionBroadcastActor logs failed to send transactions as it is noticed in the …

DEX-343 Matching Rules API

---

build.sbt
dex/build.sbt
dex/src/main/scala/com/wavesplatform/dex/Matcher.scala
dex/src/main/scala/com/wavesplatform/dex/api/http/CompositeHttpService.scala
dex/src/main/scala/com/wavesplatform/dex/api/http/SwaggerDocService.scala
dex/src/test/scala/com/wavesplatform/state/diffs/package.scala

* Updated the NODE dependency to 1.0.1. Fixed upgrade issues;
* Added own CompositeHttpService and SwaggerDocService, because the NODE ones contain an incorrect for DEX information;
* Version.scala is generated for DEX.

DEX-351 Show the DEX's version in Swagger

---

build.sbt
dex/src/main/scala/com/wavesplatform/dex/AddressActor.scala
dex/src/main/scala/com/wavesplatform/dex/MatcherTool.scala
dex/src/main/scala/com/wavesplatform/dex/api/MatcherApiRoute.scala
dex/src/main/scala/com/wavesplatform/dex/model/MatcherModel.scala
dex/src/main/scala/com/wavesplatform/dex/model/OrderInfo.scala
dex/src/main/scala/com/wavesplatform/dex/util/Codecs.scala
dex/src/test/scala/com/wavesplatform/dex/model/OrderDBSpec.scala
dex/src/test/scala/com/wavesplatform/dex/model/OrderHistoryBalanceSpecification.scala
dex/src/test/scala/com/wavesplatform/dex/model/OrderInfoSpec.scala
project/plugins.sbt

Migration:
This migration is idempotent and leaves the DB in the correct state even it ran multiple times.
Example of command for Mainnet with specified arguments: "sudo -u waves -main com.wavesplatform.dex.MatcherTool /path/to/config oi-migrate <useFast> <from>"
Arguments:
* They are optional, but you must to specify both if want to specify "from" without "useFast";
* "useFast" can be "true", if your DEX accepts only the base coin (for Waves network it is WAVES) and works in the "dynamic" mode. If you are not sure, use "false".
The fast migration works 3-4 times faster than the correct one and processes 100 millions of orders in ≈5 minutes;
* "from" if you ran migration previously and want to skip processed orders. Note, that skipping is not a fast operation (but it does less work). If …

DEX-352 The matcher fee in REST API

---

dex-it/src/test/scala/com/wavesplatform/it/sync/smartcontracts/OrdersFromScriptedAccTestSuite.scala
dex-it/src/test/scala/com/wavesplatform/it/sync/smartcontracts/ProofAndAssetPairTestSuite.scala
dex/src/main/scala/com/wavesplatform/dex/error/package.scala
dex/src/main/scala/com/wavesplatform/dex/model/OrderValidator.scala
dex/src/main/scala/com/wavesplatform/dex/smart/MatcherContext.scala
dex/src/main/scala/com/wavesplatform/dex/smart/MatcherScriptRunner.scala
dex/src/test/scala/com/wavesplatform/dex/error/ProduceError.scala
dex/src/test/scala/com/wavesplatform/dex/model/OrderValidatorSpecification.scala
dex/src/test/scala/com/wavesplatform/dex/smart/MatcherScriptRunnerTest.scala

* A blockchain access during an order's validation now denied on higher level. All new functions those doesn't require a blockchain's access will be supported automatically;
* Error messages now contains blockchain's functions instead of the script ones. Waiting for a fix from Smart Contracts;
* Fixed a bug with order's validation on dApp script;
Internals:
* OrderValidator. verifyOrderByAccountScript tracing exceptions;
* MatcherContext now is BlockchainContext (used in a normal scenario), but with mocked Blockchain: all methods throw SecurityException;
* MatcherScriptRunner works correctly with dApps;
Tests:
* com.wavesplatform.dex.error.ProduceError with regular expressions;
* Added MatcherScriptRunnerTest;

DEX-361 dApp execution error during order placement

---

dex-it/src/test/scala/com/wavesplatform/it/sync/OrderV3TestSuite.scala

Integration tests of disable/enable orders V3 by "waves.dex { allowed-order-versions = [1, 2, 3] }" setting

DEX-121 matcher settings for OrderV3

---

.travis.yml
dex/src/main/resources/application.conf
dex/src/main/scala/com/wavesplatform/dex/api/OrderBookSnapshotHttpCache.scala
dex/src/test/scala/com/wavesplatform/dex/api/OrderBookSnapshotHttpCacheSpec.scala
dex/src/test/scala/com/wavesplatform/dex/settings/MatcherSettingsSpecification.scala

Introduced waves.dex.order-book-snapshot-http-cache.default-depth

DEX-385 Order books: configurable depth for responses

---

README.md
build.sbt
dex/dex-stagenet.conf
dex/src/main/scala/com/wavesplatform/dex/api/MatcherApiRoute.scala
dex/src/main/scala/com/wavesplatform/dex/api/http/CompositeHttpService.scala
dex/src/main/scala/com/wavesplatform/dex/doc/DocGeneratorApp.scala
dex/src/main/scala/com/wavesplatform/dex/market/MatcherActor.scala
dex/src/main/scala/com/wavesplatform/dex/model/ExchangeTransactionCreator.scala
dex/src/main/scala/com/wavesplatform/dex/model/OrderValidator.scala
dex/src/main/scala/com/wavesplatform/dex/smart/MatcherContext.scala
dex/src/test/scala/com/wavesplatform/state/diffs/package.scala
project/CommonSettings.scala
project/Dependencies.scala
project/ItTestPlugin.scala
project/ModernJavaSettings.scala
project/Network.scala
project/ReleasePlugin.scala
project/plugins.sbt

DEX-395 Java 11 support:
* Added support of Java 11;
* Fixed issues with loading Swagger resource files in a browser;
* Added DocGeneratorApp to support "release" task (MatcherTool has gone);
* Updated README.md, now it contains instructions about a Java 11 installation;
* Fixed issues after migration to Node 1.1.0;
DEX-389 Stagenet support;
DEX-370 Force creation of order books' snapshots;

DEX-395 Java 11 support

---

dex/src/main/scala/com/wavesplatform/dex/model/OrderBook.scala
dex/src/test/scala/com/wavesplatform/dex/MatcherTestData.scala
dex/src/test/scala/com/wavesplatform/dex/model/OrderBookSpec.scala
dex/src/test/scala/com/wavesplatform/dex/model/OrderValidatorSpecification.scala

Now old orders with different or disabled tick-size can be matched with the submitted orders with new tick-size

DEX-412 Old orders matching fix

---

build.sbt
dex-it/src/test/scala/com/wavesplatform/it/sync/MatchingRulesTestSuite.scala
dex/src/main/scala/com/wavesplatform/dex/Matcher.scala
dex/src/main/scala/com/wavesplatform/dex/api/MatcherApiRoute.scala
dex/src/main/scala/com/wavesplatform/dex/caches/MatchingRulesCache.scala
dex/src/main/scala/com/wavesplatform/dex/caches/RateCache.scala
dex/src/main/scala/com/wavesplatform/dex/market/OrderBookActor.scala
dex/src/main/scala/com/wavesplatform/dex/model/OrderBook.scala
dex/src/main/scala/com/wavesplatform/dex/model/OrderValidator.scala
dex/src/main/scala/com/wavesplatform/dex/settings/MatchingRule.scala
dex/src/test/scala/com/wavesplatform/dex/MatcherTestData.scala
dex/src/test/scala/com/wavesplatform/dex/api/MatcherApiRouteSpec.scala
dex/src/test/scala/com/wavesplatform/dex/model/OrderBookSpec.scala
dex/src/test/scala/com/wavesplatform/dex/model/OrderValidatorSpecification.scala

* Price level 0 for buy orders is firbidden;
* Matching rules cache introduced;
* Matching rules inside Matcher refactored;
* Order book info now displays tick-size for the next order

DEX-404 Zero price level is forbidden

---

dex-it/src/test/scala/com/wavesplatform/it/sync/MatchingRulesTestSuite.scala
dex-it/src/test/scala/com/wavesplatform/it/sync/OrderRestrictionsTestSuite.scala
dex/src/main/scala/com/wavesplatform/dex/Matcher.scala
dex/src/main/scala/com/wavesplatform/dex/caches/MatchingRulesCache.scala
dex/src/main/scala/com/wavesplatform/dex/settings/MatchingRule.scala
dex/src/main/scala/com/wavesplatform/dex/settings/package.scala

* Matching rules now correctly set for new order books;
* Tick size formatting fixed for the tricky pairs like wct/Waves

DEX-404 Matching rules cache fix

---

build.sbt
dex/build.sbt
waves-integration/src/main/scala/com/wavesplatform/dex/grpc/integration/caches/AssetDescriptionsCache.scala
waves-integration/src/main/scala/com/wavesplatform/dex/grpc/integration/caches/BalancesCache.scala
waves-integration/src/main/scala/com/wavesplatform/dex/grpc/integration/caches/BlockchainCache.scala
waves-integration/src/main/scala/com/wavesplatform/dex/grpc/integration/caches/FeaturesCache.scala
waves-integration/src/main/scala/com/wavesplatform/dex/grpc/integration/clients/async/WavesBlockchainCachingClient.scala
waves-integration/src/test/scala/com/wavesplatform/dex/grpc/integration/caches/BlockchainCacheSpecification.scala

Blockchain caches now don't keep failed futures and undesirable results according to the predicate

DEX-401 Custom further processing of the loading results in gRPC caches

---

dex/src/main/scala/com/wavesplatform/dex/api/http/SwaggerDocService.scala

before changes: we showed the node's version in swagger page
after changes: we show the dex's version

DEX version in swagger

---

dex/src/main/resources/application.conf
dex/src/main/scala/com/wavesplatform/dex/Matcher.scala
dex/src/main/scala/com/wavesplatform/dex/api/MatcherApiRoute.scala
dex/src/main/scala/com/wavesplatform/dex/api/MatcherApiRouteV1.scala
dex/src/main/scala/com/wavesplatform/dex/api/http/AuthRoute.scala
dex/src/main/scala/com/wavesplatform/dex/error/MatcherError.scala
dex/src/test/scala/com/wavesplatform/dex/api/MatcherApiRouteSpec.scala

* DEX's withAuth introduced
* apiKey now passed to the MatcherApiRoute/V1 as optional byte array
* Checking apiKeyHash during matcher's start
* ApiKeyIsNoProvided and ApiKeyIsNotValid matcher errors introduced

DEX-492 withAuth refactoring

---

dex-it/src/test/scala/com/wavesplatform/it/api/AsyncMatcherHttpApi.scala
dex-it/src/test/scala/com/wavesplatform/it/api/SyncMatcherHttpApi.scala
dex-it/src/test/scala/com/wavesplatform/it/sync/OrderRestrictionsTestSuite.scala
dex/src/main/scala/com/wavesplatform/dex/api/MatcherApiRoute.scala
dex/src/main/scala/com/wavesplatform/dex/api/MatcherResponse.scala
dex/src/main/scala/com/wavesplatform/dex/error/MatcherError.scala
dex/src/test/scala/com/wavesplatform/dex/api/MatcherApiRouteSpec.scala

* Unified rejections handling for Json parsing errors added (copied from the master branch)
* InvalidRateInput error removed
* Order placement by JsObject in it-tests

DEX-515 Correct matcher response for the invalid order json

---

dex/src/main/scala/com/wavesplatform/dex/error/MatcherError.scala
dex/src/main/scala/com/wavesplatform/dex/model/MatcherModel.scala
dex/src/test/scala/com/wavesplatform/dex/model/OrderValidatorSpecification.scala

* UnexpectedFeeAsset error improved
Refactoring
* Code duplication in MatcherModel (MarketOrder object) fixed

DEX-462 Better error for WAVES as Base58 in matcherFeeAssetId field

---

dex-it/src/test/scala/com/wavesplatform/it/api/model.scala
dex-it/src/test/scala/com/wavesplatform/it/sync/MarketOrderTestSuite.scala
dex-it/src/test/scala/com/wavesplatform/it/sync/MatcherTestSuite.scala
dex/src/main/scala/com/wavesplatform/dex/AddressActor.scala
dex/src/main/scala/com/wavesplatform/dex/api/MatcherApiRoute.scala
dex/src/main/scala/com/wavesplatform/dex/model/AcceptedOrderType.scala
dex/src/main/scala/com/wavesplatform/dex/model/OrderInfo.scala
dex/src/main/scala/com/wavesplatform/dex/util/Codecs.scala

Model:
* Added AcceptedOrderType with two members: Limit and Market;
* OrderInfo: added the 3 version with orderType;
* Implemented a new serialization/deserialization for new OrderInfo in bytes;
MatcherApiRoute:
* Added "orderType" in JSON of getAssetPairAndPublicKeyOrderHistory, getPublicKeyOrderHistory and admin's getAllOrderHistory;
Integration tests:
* Added tests to check order types for both Limit and Market orders;

DEX-537 Distinguishing limit and market orders in order history

---

build.sbt
dex-it/src/test/resources/template.conf
dex/src/main/scala/com/wavesplatform/dex/smart/MatcherContext.scala

DEX-478 Prepare to release 1.1.0

---

dex-it-common/src/main/scala/com/wavesplatform/dex/it/config/PredefinedAssets.scala
dex-it-common/src/main/scala/com/wavesplatform/dex/it/waves/MkWavesEntities.scala
dex-it/src/test/scala/com/wavesplatform/it/sync/MarketOrderTestSuite.scala
dex-it/src/test/scala/com/wavesplatform/it/sync/PostgresHistoryDatabaseTestSuite.scala
dex-test-common/src/main/scala/com/wavesplatform/dex/asset/DoubleOps.scala
waves-integration/src/main/scala/com/wavesplatform/dex/domain/order/OrderV1.scala
waves-integration/src/main/scala/com/wavesplatform/dex/domain/transaction/ExchangeTransactionV1.scala

* mkOrderDP introduced (accepts prices of type double)
* PostgresHistoryDatabaseTestSuite is rewritten in mkOrderDP style

DEX-524 Creation of the orders with denormalized price in it-tests

---

dex-it/src/test/scala/com/wavesplatform/it/sync/TradersTestSuite.scala
waves-ext/src/main/scala/com/wavesplatform/dex/grpc/integration/services/WavesBlockchainApiGrpcService.scala

* WavesBlockchainApiGrpcService uses `context.utx.spendableBalance` instead of `context.blockchain.balance`
* IT test added

DEX-592 Considering UTX during obtaining of the spendable balance

---

dex/build.sbt
project/VersionSourcePlugin.scala
waves-ext/build.sbt

* VersionSourcePlugin introduced
* Modules dex and waves-ext now use this plugin (code duplication fixed)

DEX-579 Version task sbt plugin

---

dex/build.sbt
dex/src/main/resources/application.conf
dex/src/main/scala/com/wavesplatform/dex/Application.scala
dex/src/package/debian/postinst
dex/src/package/doc/logback.xml
project/RewriteSwaggerConfigPlugin.scala
project/build.properties
waves-ext/build.sbt
waves-integration/src/main/scala/com/wavesplatform/dex/domain/asset/Asset.scala

* Application: sets waves.dex.root-directory from the config, if it wasn't set up;
* RewriteSwaggerConfigPlugin: selects HTTPS if we on the HTTPS page;
* logback.xml: waves.directory is not used, replaced by waves.dex.root-directory instead;
* application.conf: changed the default loglevel;
* null instead of WAVES in /matcher/settings;
* Added default memory limits;

DEX-603 Logging and configuration issues

---

README.md
dex-it-common/src/main/scala/com/wavesplatform/dex/it/api/BaseContainersKit.scala
dex-it-common/src/main/scala/com/wavesplatform/dex/it/docker/BaseContainer.scala
dex-it-common/src/main/scala/com/wavesplatform/dex/it/test/InformativeTestStart.scala
dex-it/src/test/scala/com/wavesplatform/it/sync/networking/DexClientFaultToleranceTestSuite.scala
dex/src/main/scala/com/wavesplatform/dex/AddressActor.scala
dex/src/main/scala/com/wavesplatform/dex/Matcher.scala
dex/src/main/scala/com/wavesplatform/dex/queue/KafkaMatcherQueue.scala
project/Dependencies.scala
waves-ext/src/main/resources/application.conf
waves-ext/src/main/scala/com/wavesplatform/dex/grpc/integration/DEXExtension.scala
waves-ext/src/main/scala/com/wavesplatform/dex/grpc/integration/services/WavesBlockchainApiGrpcService.scala
waves-integration/src/main/scala/com/wavesplatform/dex/grpc/integration/clients/WavesBlockchainGrpcAsyncClient.scala

* Better error handling and stop procedure for gRPC;
* Fixed the shutdown including Kafka errors;
* A separate thread pool for gRPC service on DEX extension;
Integration tests:
* Containers in tests are shut down in a reversed to initialization order;
* Fixed NotModifiedException if a container already stopped;

DEX-606 Graceful stop

---

dex/src/main/scala/com/wavesplatform/dex/AddressDirectory.scala
waves-ext/src/main/scala/com/wavesplatform/dex/grpc/integration/services/WavesBlockchainApiGrpcService.scala

* AddressDirectory.spendableBalanceChanges now uses a state of AddressDirectory through message passing;
* WavesBlockchainApiGrpcService detects when a balance changes stream is closed by a client;

DEX-638 Fixes for balance stream

---

dex-test-common/src/main/scala/com/wavesplatform/dex/test/matchers/DiffMatcherWithImplicits.scala
dex/src/main/scala/com/wavesplatform/dex/AddressActor.scala
dex/src/test/scala/com/wavesplatform/dex/AddressActorSpecification.scala

* Fixed the bug;
* Matching errors are written through ScalaTest's MatchResult;

DEX-652 Excess assets in reservable assets request

---

dex-it-common/src/main/scala/com/wavesplatform/dex/it/api/dex/DexApi.scala
dex-it/src/test/scala/com/wavesplatform/it/sync/MatcherMassOrdersTestSuite.scala
dex-it/src/test/scala/com/wavesplatform/it/sync/MatcherTestSuite.scala
dex-it/src/test/scala/com/wavesplatform/it/sync/PostgresHistoryDatabaseTestSuite.scala
dex-it/src/test/scala/com/wavesplatform/it/sync/RestOrderLimitTestSuite.scala
dex/src/main/resources/application.conf
dex/src/main/scala/com/wavesplatform/dex/AddressActor.scala
dex/src/main/scala/com/wavesplatform/dex/Matcher.scala
dex/src/main/scala/com/wavesplatform/dex/db/OrderDB.scala
dex/src/main/scala/com/wavesplatform/dex/model/OrderValidator.scala
dex/src/main/scala/com/wavesplatform/dex/settings/MatcherSettings.scala
dex/src/test/scala/com/wavesplatform/dex/AddressActorSpecification.scala
dex/src/test/scala/com/wavesplatform/dex/db/EmptyOrderDB.scala
dex/src/test/scala/com/wavesplatform/dex/db/TestOrderDB.scala
dex/src/test/scala/com/wavesplatform/dex/matching/ReservedBalanceSpecification.scala
dex/src/test/scala/com/wavesplatform/dex/model/OrderDBSpec.scala
dex/src/test/scala/com/wavesplatform/dex/model/OrderHistoryBalanceSpecification.scala
dex/src/test/scala/com/wavesplatform/dex/model/OrderHistoryStub.scala
dex/src/test/scala/com/wavesplatform/dex/settings/BaseSettingsSpecification.scala
dex/src/test/scala/com/wavesplatform/dex/settings/MatcherSettingsSpecification.scala
project/Dependencies.scala

Simplified a logic for getting order history from REST API.
Was:
There was a setting: `rest-order-limit`.
DEX loaded active orders and tried to fill the resulting list with closed (filled, canceled) orders to fit rest-order-limit, if it is able.
Now:
There are new settings: `max-active-orders` and `order-db.max-orders`.
DEX loads all active orders (up to `max-active-orders`) and all closed orders (up to `order-db.max-orders`).

DEX-643 Max active orders

---

dex-it/src/test/scala/com/wavesplatform/it/sync/MatchingRulesTestSuite.scala
dex-it/src/test/scala/com/wavesplatform/it/sync/api/MatcherWebSocketsTestSuite.scala
dex-test-common/src/main/scala/com/wavesplatform/dex/test/matchers/DiffMatcherWithImplicits.scala
dex/src/main/scala/com/wavesplatform/dex/AddressActor.scala
dex/src/main/scala/com/wavesplatform/dex/AddressDirectory.scala
dex/src/main/scala/com/wavesplatform/dex/AddressWsMutableState.scala
dex/src/main/scala/com/wavesplatform/dex/history/HistoryRouter.scala
dex/src/main/scala/com/wavesplatform/dex/model/MatcherModel.scala
dex/src/main/scala/com/wavesplatform/dex/model/OrderBook.scala
dex/src/test/scala/com/wavesplatform/dex/ActorsWebSocketInteractionsSpecification.scala
dex/src/test/scala/com/wavesplatform/dex/market/OrderBookActorSpecification.scala
dex/src/test/scala/com/wavesplatform/dex/matching/ReservedBalanceSpecification.scala
dex/src/test/scala/com/wavesplatform/dex/model/OrderBookSpec.scala
dex/src/test/scala/com/wavesplatform/dex/model/OrderBookTestSuite.scala

Fixed:
* Send the full market order on place;
* Send only changes for MarketOrder, when it is filled;
Domain:
* OrderBook: always generate OrderAdded;
* OrderStatus.finalStatus is renamed to finalCancelStatus, because it used only for OrderCanceled;
Now we know clearly when an order appears first time, thus:
* AddressActor - simplified events processing;
* AddressDirectory - simplified message forwarding to order history;
* AddressWsMutableState.trackedOrders is removed;
Tests:
* Fixed coloring in DiffMatcherWithImplicits;
Other:
* AddressActor uses a regular group for Map (code is less difficult to interpret);

DEX-647 Refactor events generated by OrderBook

---

dex-it-common/src/main/scala/com/wavesplatform/dex/it/api/responses/dex/OrderBookHistoryItem.scala
dex-it/src/test/scala/com/wavesplatform/it/sync/OrderHistoryTestSuite.scala
dex-it/src/test/scala/com/wavesplatform/it/sync/api/MatcherWebSocketsTestSuite.scala
dex/src/main/scala/com/wavesplatform/dex/AddressActor.scala
dex/src/main/scala/com/wavesplatform/dex/AddressWsMutableState.scala
dex/src/main/scala/com/wavesplatform/dex/api/MatcherApiRoute.scala
dex/src/main/scala/com/wavesplatform/dex/api/websockets/WsOrder.scala
dex/src/main/scala/com/wavesplatform/dex/model/AcceptedOrderType.scala
dex/src/main/scala/com/wavesplatform/dex/model/MatcherModel.scala
dex/src/main/scala/com/wavesplatform/dex/model/OrderBook.scala
dex/src/main/scala/com/wavesplatform/dex/model/OrderBookSideSnapshot.scala
dex/src/main/scala/com/wavesplatform/dex/model/OrderBookSnapshot.scala
dex/src/main/scala/com/wavesplatform/dex/model/OrderInfo.scala
dex/src/main/scala/com/wavesplatform/dex/util/Codecs.scala
dex/src/test/scala/com/wavesplatform/dex/ActorsWebSocketInteractionsSpecification.scala
dex/src/test/scala/com/wavesplatform/dex/AddressActorSpecification.scala
dex/src/test/scala/com/wavesplatform/dex/MatcherSpecBase.scala
dex/src/test/scala/com/wavesplatform/dex/api/websockets/WebSocketMessagesSerdeSpecification.scala
dex/src/test/scala/com/wavesplatform/dex/gen/OrderBookGen.scala
dex/src/test/scala/com/wavesplatform/dex/market/OrderBookActorSpecification.scala
dex/src/test/scala/com/wavesplatform/dex/model/OrderBookSpec.scala
dex/src/test/scala/com/wavesplatform/dex/model/OrderBookTestSuite.scala
dex/src/test/scala/com/wavesplatform/dex/model/OrderHistoryBalanceSpecification.scala
dex/src/test/scala/com/wavesplatform/dex/model/OrderInfoSpec.scala
waves-integration/src/main/scala/com/wavesplatform/dex/domain/order/Order.scala

* AcceptedOrder has been enriched with avgWeighedPriceNominator. Dividing this by filledAmount we got avgWeighedPrice
* OrderInfo v4 has been introduced (it has new field avgWeighedPrice). For old orders avgWeighedPrice will be equal to order price
* AddressActor uses OrderInfo v4 and sends correct avgWeighedPrice via WebSockets
* OrderBookSideSnapshot got new serialization of LimitOrder with backward compatibility
* Unit and it-tests have been added
Miscellaneous
* limitOrderFormat has been removed from OrderBook
* AcceptedOrder.fold removed

DEX-594 Average weighed price

---

dex-it-common/src/main/scala/com/wavesplatform/dex/it/api/BaseContainersKit.scala
dex-it-common/src/main/scala/com/wavesplatform/dex/it/api/dex/DexApi.scala
dex-it-common/src/main/scala/com/wavesplatform/dex/it/api/dex/DexApiOps.scala
dex-it/src/test/resources/dex-servers/dex-base.conf
dex-it/src/test/scala/com/wavesplatform/it/sync/CancelOrderTestSuite.scala
dex/src/main/scala/com/wavesplatform/dex/AddressActor.scala
dex/src/main/scala/com/wavesplatform/dex/api/MatcherApiRoute.scala
dex/src/main/scala/com/wavesplatform/dex/api/http/AuthRoute.scala
dex/src/main/scala/com/wavesplatform/dex/api/http/`X-Api-Key`.scala
dex/src/main/scala/com/wavesplatform/dex/api/http/`X-User-Public-Key`.scala
dex/src/main/scala/com/wavesplatform/dex/error/MatcherError.scala
dex/src/main/scala/com/wavesplatform/dex/market/BatchOrderCancelActor.scala
dex/src/test/scala/com/wavesplatform/dex/api/MatcherApiRouteSpec.scala

Bug fixes:
* Batch cancels don't return the latest order status;
MatcherApiRoute:
* Added cancelAllById to cancel orders by a list of order ids;
* forceCancelOrder - additional check by X-User-Public-Key if it present;
* reservedBalance - also works by X-Api-Key;
AddressActor: supports CancelOrders;
BatchOrderCancelActor: the final response could be prepared with some initial value (e.g. some orders aren't found among users orders);
Other:
* Added a new error: UserPublicKeyIsNotValid;
* Added X-User-Public-Key to additionally verify some admin requests;
Tests:
* DexApi: added tryCancelAllByIdsWithApiKey;
* Disable caches for sync API;

DEX-661 REST API improvements

---

dex-it-common/src/main/scala/com/wavesplatform/dex/it/api/websockets/HasWebSockets.scala
dex-it-common/src/main/scala/com/wavesplatform/dex/it/api/websockets/WebSocketAuthenticatedConnection.scala
dex-it-common/src/main/scala/com/wavesplatform/dex/it/api/websockets/WebSocketConnection.scala
dex-it/src/test/scala/com/wavesplatform/it/sync/api/MatcherWebSocketsTestSuite.scala
dex/src/main/scala/com/wavesplatform/dex/Matcher.scala
dex/src/main/scala/com/wavesplatform/dex/api/MatcherWebSocketRoute.scala
dex/src/main/scala/com/wavesplatform/dex/api/http/AuthRoute.scala
dex/src/main/scala/com/wavesplatform/dex/api/websockets/headers/`X-Error-Code`.scala
dex/src/main/scala/com/wavesplatform/dex/api/websockets/headers/`X-Error-Message`.scala
dex/src/main/scala/com/wavesplatform/dex/error/MatcherError.scala

* Connection to authenticated balance stream can be done via correct timestamp and signature or X-API-Key. X-API-Key has the highest priority, with correct signature and incorrect key stream connection won't be established
* WS connection responses have X-Error-Message and X-Error-Code headers
* withAuth creates simple response or response with aforementioned headers for different types of Routes
* It-test added

DEX-666 API key in authenticated WS stream

---

dex-it/src/test/scala/com/wavesplatform/it/sync/CancelOrderTestSuite.scala
dex-it/src/test/scala/com/wavesplatform/it/sync/MultipleMatchersTestSuite.scala
dex/src/main/scala/com/wavesplatform/dex/AddressActor.scala
dex/src/main/scala/com/wavesplatform/dex/Matcher.scala
dex/src/main/scala/com/wavesplatform/dex/model/ExchangeTransactionCreator.scala
dex/src/main/scala/com/wavesplatform/dex/model/Fee.scala
dex/src/main/scala/com/wavesplatform/dex/model/MatcherModel.scala
dex/src/main/scala/com/wavesplatform/dex/model/OrderBook.scala
dex/src/main/scala/com/wavesplatform/dex/model/OrderValidator.scala
dex/src/test/scala/com/wavesplatform/dex/MatcherSpecBase.scala
dex/src/test/scala/com/wavesplatform/dex/history/HistoryRouterSpecification.scala
dex/src/test/scala/com/wavesplatform/dex/market/MatcherActorSpecification.scala
dex/src/test/scala/com/wavesplatform/dex/market/OrderBookActorSpecification.scala
dex/src/test/scala/com/wavesplatform/dex/matching/ReservedBalanceSpecification.scala
dex/src/test/scala/com/wavesplatform/dex/model/EventSpecification.scala
dex/src/test/scala/com/wavesplatform/dex/model/ExchangeTransactionCreatorSpecification.scala
dex/src/test/scala/com/wavesplatform/dex/model/FeeSpecification.scala
dex/src/test/scala/com/wavesplatform/dex/model/OrderBookSpec.scala
dex/src/test/scala/com/wavesplatform/dex/model/OrderHistoryBalanceSpecification.scala
dex/src/test/scala/com/wavesplatform/dex/model/OrderValidatorSpecification.scala

Fee: an object with functions to calculate fees;
OrderExecuted: counterExecutedFee and submittedRemainingFee now are static and not calculated;
ExchangeTransactionCreator now uses calculated fees from the OrderExecuted event;
CancelOrderTestSuite:
* A new integration test to check this bug;
* Test stabilization;
ExchangeTransactionCreatorSpecification: some tests migrated to FeeSpecification and OrderBookActorSpecification;

DEX-677 Wrong order cancel

---

dex-it-common/src/main/scala/com/wavesplatform/dex/it/api/dex/DexApi.scala
dex-it/src/test/scala/com/wavesplatform/it/sync/api/GetOrderBookTestSuite.scala
dex/src/main/scala/com/wavesplatform/dex/api/MatcherApiRoute.scala

* Loss of query parameter `depth` during redirect (orderBook endpoint) fixed
* GetOrderBookTestSuite fixed

DEX-695 Fix of query parameter loss during redirect

---

README.md

I had the issue hat I put the config snipped into /usr/share/waves/conf/waves.conf which is accepted is syntactically not missplaced.

Clarify the location of the "matcher server configuration"

---

dex-it/src/test/scala/com/wavesplatform/it/sync/api/ws/WebSocketPrivateStreamTestSuite.scala
dex/src/main/scala/com/wavesplatform/dex/api/websockets/WsAddressState.scala
dex/src/test/scala/com/wavesplatform/dex/ActorsWebSocketInteractionsSpecification.scala
waves-ext/src/main/scala/com/wavesplatform/dex/grpc/integration/services/WavesBlockchainApiGrpcService.scala

* Method allAssetsSpendableBalance in WavesBlockchainApiGrpcService returns only nonzero balances
* Unit and integration tests added

DEX-686 Empty balances for new accounts in WS private streams

---

dex-it/src/test/scala/com/wavesplatform/it/sync/api/ws/WebSocketPublicStreamTestSuite.scala
dex-it/src/test/scala/com/wavesplatform/it/sync/api/ws/WsConnectionTestSuite.scala
dex/src/main/scala/com/wavesplatform/dex/AddressActor.scala
dex/src/main/scala/com/wavesplatform/dex/AddressWsMutableState.scala
dex/src/main/scala/com/wavesplatform/dex/OrderBookWsState.scala
dex/src/main/scala/com/wavesplatform/dex/actors/OrderBookAskAdapter.scala
dex/src/main/scala/com/wavesplatform/dex/api/MatcherWebSocketRoute.scala
dex/src/main/scala/com/wavesplatform/dex/api/websockets/WsMessage.scala
dex/src/main/scala/com/wavesplatform/dex/api/websockets/actors/SystemMessagesHandlerActor.scala
dex/src/main/scala/com/wavesplatform/dex/api/websockets/statuses/TerminationStatus.scala
dex/src/main/scala/com/wavesplatform/dex/error/MatcherError.scala
dex/src/main/scala/com/wavesplatform/dex/market/AggregatedOrderBookActor.scala
dex/src/main/scala/com/wavesplatform/dex/market/OrderBookActor.scala
dex/src/test/scala/com/wavesplatform/dex/ActorsWebSocketInteractionsSpecification.scala
dex/src/test/scala/com/wavesplatform/dex/api/AggregatedOrderBookActorSpec.scala
dex/src/test/scala/com/wavesplatform/dex/api/http/OrderBookHttpInfoSpec.scala
project/Dependencies.scala

* AggregatedOrderBookActor closes all WS connections on PostStop signal
* ConnectionSource removed, typed ActorRef is used instead
* TerminationStatus removed, MatcherError is used instead
* WsConnectionPongTimeout and WsConnectionMaxLifetimeExceeded matcher errors introduced
* Used typed actor as a recipient of changes in AddressActor
* ActorsWebSocketInteractionsSpecification rewritten in typed ActorRef style
* WS connections now have a UUID in names

DEX-681 Closing all WS connections after order book deleting

---

dex-it/src/test/scala/com/wavesplatform/it/sync/api/ws/WebSocketPublicStreamTestSuite.scala
dex/src/main/scala/com/wavesplatform/dex/Matcher.scala
dex/src/main/scala/com/wavesplatform/dex/OrderBookWsState.scala
dex/src/main/scala/com/wavesplatform/dex/api/websockets/WsOrderBook.scala
dex/src/main/scala/com/wavesplatform/dex/api/websockets/WsOrderBookSettings.scala
dex/src/main/scala/com/wavesplatform/dex/market/AggregatedOrderBookActor.scala
dex/src/main/scala/com/wavesplatform/dex/market/OrderBookActor.scala
dex/src/main/scala/com/wavesplatform/dex/model/OrderValidator.scala
dex/src/test/scala/com/wavesplatform/dex/api/AggregatedOrderBookActorSpec.scala
dex/src/test/scala/com/wavesplatform/dex/api/http/OrderBookHttpInfoSpec.scala
dex/src/test/scala/com/wavesplatform/dex/api/websockets/WebSocketMessagesSerdeSpecification.scala
dex/src/test/scala/com/wavesplatform/dex/market/MatcherActorSpecification.scala
dex/src/test/scala/com/wavesplatform/dex/market/OrderBookActorSpecification.scala
dex/src/test/scala/com/wavesplatform/dex/model/OrderValidatorSpecification.scala
project/Dependencies.scala

* Order book settings are sent in snapshot
- WsOrderBookSettings introduced
- Unit and integration tests added
- Using of OrderRestrictionsSettings in OrderValidator refactored
* Changes of tick-size are sent to WS API public stream
- Using lenses for modifying of AggregatedOrderBookActor state
* Unit and integration tests added

DEX-720 Order book settings in public WS API stream

---

dex-it/src/test/scala/com/wavesplatform/it/sync/api/ws/WsPingPongTestSuite.scala
dex/src/main/scala/com/wavesplatform/dex/api/MatcherWebSocketRoute.scala
dex/src/main/scala/com/wavesplatform/dex/api/websockets/actors/WsHandlerActor.scala
dex/src/main/scala/com/wavesplatform/dex/market/AggregatedOrderBookActor.scala
dex/src/main/scala/com/wavesplatform/dex/market/OrderBookActor.scala

* WsHandlerActor the closing logic changed, no deadletter messages now;
* AggregatedOrderBookActor - returned a previous way to notify clients about removed order book. The client will not receive a message about a deleted order book when the server is stopping;
* WsPingPongTestSuite: now checks that a client receives WsConnectionMaxLifetimeExceeded and WsConnectionPongTimeout before the connection is closed due to one of this reasons;

DEX-699 Errors during WebSocket connection

---

dex-it-common/src/main/scala/com/wavesplatform/dex/it/matchers/ItMatchers.scala
dex-it/src/test/scala/com/wavesplatform/it/sync/MarketOrderTestSuite.scala
dex-it/src/test/scala/com/wavesplatform/it/sync/orders/OrderPercentFeeAmountTestSuite.scala
dex-it/src/test/scala/com/wavesplatform/it/sync/orders/OrderPercentFeePriceTestSuite.scala
dex/src/main/scala/com/wavesplatform/dex/error/MatcherError.scala

* BalanceNotEnough error now has determined order of assets
* failWithBalanceNotEnough matcher introduced
* Integration tests fixed

DEX-726 Order assets in BalanceNotEnough Error

---

dex-it-common/src/main/scala/com/wavesplatform/dex/it/api/websockets/HasJwt.scala
dex-it-common/src/main/scala/com/wavesplatform/dex/it/api/websockets/HasWebSockets.scala
dex-it/src/test/scala/com/wavesplatform/it/WsSuiteBase.scala
dex-it/src/test/scala/com/wavesplatform/it/sync/api/ws/WsAddressStreamTestSuite.scala
dex-it/src/test/scala/com/wavesplatform/it/sync/api/ws/WsConnectionTestSuite.scala
dex-it/src/test/scala/com/wavesplatform/it/sync/api/ws/WsOrderBookStreamTestSuite.scala
dex-it/src/test/scala/com/wavesplatform/it/sync/api/ws/WsPingPongTestSuite.scala
dex/src/main/scala/com/wavesplatform/dex/AddressWsMutableState.scala
dex/src/main/scala/com/wavesplatform/dex/OrderBookWsState.scala
dex/src/main/scala/com/wavesplatform/dex/api/websockets/WsAddressSubscribe.scala
dex/src/main/scala/com/wavesplatform/dex/api/websockets/actors/WsHandlerActor.scala
dex/src/main/scala/com/wavesplatform/dex/error/MatcherError.scala
dex/src/main/scala/com/wavesplatform/dex/market/AggregatedOrderBookActor.scala
dex/src/test/scala/com/wavesplatform/dex/api/websockets/WsHandlerActorSpec.scala

Main:
* Cancelling of the address subscription schedules right after subscribe request;
* Subscription lifetime can be extended by updated jwt token in new subscribe request;
* CancelAddressSubscription command in WsHandlerActor introduced;
* Unit and integration tests added;
* Minor improvements in AddressWsMutableState and OrderBookWsState
Errors:
* SubscriptionTokenExpired got address argument
Tests:
* WsError timestamp is ignored in WsSuiteBase

DEX-733 Address subscription cancelling after JWT expiration

---

dex-it/src/test/scala/com/wavesplatform/it/sync/networking/DexClientFaultToleranceTestSuite.scala
dex/src/main/scala/com/wavesplatform/dex/AddressActor.scala
dex/src/main/scala/com/wavesplatform/dex/AddressWsMutableState.scala
dex/src/main/scala/com/wavesplatform/dex/SpendableBalancesActor.scala
dex/src/main/scala/com/wavesplatform/dex/market/AggregatedOrderBookActor.scala
dex/src/test/scala/com/wavesplatform/dex/ActorsWebSocketInteractionsSpecification.scala
dex/src/test/scala/com/wavesplatform/dex/MatcherSpecBase.scala
dex/src/test/scala/com/wavesplatform/dex/api/websockets/WsHandlerActorSpec.scala

Main:
* SpendableBalancesActor.Reply.GetSnapshot contains Either
* SpendableBalancesActor handles errors during snapshot obtaining from Waves Node
* AddressActor sends WsError with WavesNodeConnectionBroken error to all pending subscriptions, then cancels them
* AddressWsMutableState: connections renamed to subscriptions
Tests:
* wsErrorDiff (ignored timestamp in WsError) moved to MatcherSpecBase

DEX-740 Get snapshot error handling

---

dex-it/src/test/scala/com/wavesplatform/it/sync/api/ws/WsAddressStreamTestSuite.scala
dex-it/src/test/scala/com/wavesplatform/it/sync/api/ws/WsConnectionTestSuite.scala
dex-it/src/test/scala/com/wavesplatform/it/sync/api/ws/WsOrderBookStreamTestSuite.scala
dex/src/main/resources/application.conf
dex/src/main/scala/com/wavesplatform/dex/api/websockets/actors/WsHandlerActor.scala
dex/src/main/scala/com/wavesplatform/dex/error/MatcherError.scala
dex/src/main/scala/com/wavesplatform/dex/settings/MatcherSettings.scala
dex/src/main/scala/com/wavesplatform/dex/settings/SubscriptionsSettings.scala
dex/src/test/scala/com/wavesplatform/dex/api/websockets/WsHandlerActorSpec.scala
dex/src/test/scala/com/wavesplatform/dex/settings/BaseSettingsSpecification.scala
dex/src/test/scala/com/wavesplatform/dex/settings/MatcherSettingsSpecification.scala

Main:
* Order book and address subscriptions are limited
* Multiple subscriptions for one order book don't have effect
* SubscriptionsSettings extracted in a separate file, additional validation added
* Unit and integration test added
Errors:
* SubscriptionsLimitReached error introduced
* subsciption entity introduced
Tests:
* Test of multiple WS API connections moved to WsConnectionTestSuite
Miscellaneous:
* AssetPairValidated in WsHandlerActor is Event now
* Default address and order book subscriptions limit = 10

DEX-735 WS subscriptions limits

---

dex-it-common/src/main/scala/com/wavesplatform/dex/it/api/websockets/HasWebSockets.scala
dex-it-common/src/main/scala/com/wavesplatform/dex/it/api/websockets/WsConnectionOps.scala
dex-it/src/test/scala/com/wavesplatform/it/sync/api/ws/WsPingPongTestSuite.scala
dex/src/main/scala/com/wavesplatform/dex/api/MatcherWebSocketRoute.scala
dex/src/main/scala/com/wavesplatform/dex/api/websockets/WsAddressState.scala
dex/src/main/scala/com/wavesplatform/dex/api/websockets/WsAddressSubscribe.scala
dex/src/main/scala/com/wavesplatform/dex/api/websockets/WsBalances.scala
dex/src/main/scala/com/wavesplatform/dex/api/websockets/WsInitial.scala
dex/src/main/scala/com/wavesplatform/dex/api/websockets/WsOrder.scala
dex/src/main/scala/com/wavesplatform/dex/api/websockets/WsOrderBookSettings.scala
dex/src/main/scala/com/wavesplatform/dex/api/websockets/WsServerMessage.scala
dex/src/main/scala/com/wavesplatform/dex/api/websockets/actors/WsHandlerActor.scala
dex/src/main/scala/com/wavesplatform/dex/market/AggregatedOrderBookActor.scala
dex/src/main/scala/com/wavesplatform/dex/market/OrderBookActor.scala
dex/src/test/scala/com/wavesplatform/dex/api/websockets/WsHandlerActorSpec.scala

Main:
* WsInitial server message introduced. It contains connection id and is sent to the client right after connection creation
* WsError is created with time.getTimestamp() in any places
* Unit and integration tests are fixed
Tests:
* mkWsConnection automatically checks WsInitial receiving
Minor improvements:
* Completed message in WsHandlerActor and OrderBookDeleted message in AggregatedOrderBookActor became Event
* WsServerMessage got abstract timestamp field
* Formats of some ws messages and entities got more explicit names (useful for debugging)

DEX-731 WS connection ID

---

README.md
dex-it-common/src/main/scala/com/wavesplatform/dex/it/api/HasKafka.scala
dex-it-common/src/main/scala/com/wavesplatform/dex/it/api/node/HasWavesNode.scala
dex-it-common/src/main/scala/com/wavesplatform/dex/it/dex/DexApi.scala
dex-it-common/src/main/scala/com/wavesplatform/dex/it/dex/DexApiOps.scala
dex-it-common/src/main/scala/com/wavesplatform/dex/it/dex/HasDex.scala
dex-it-common/src/main/scala/com/wavesplatform/dex/it/docker/DexContainer.scala
dex-it-common/src/main/scala/com/wavesplatform/dex/it/docker/WavesNodeContainer.scala
dex-it/src/test/java/com/wavesplatform/it/tags/DexMultipleVersions.java
dex-it/src/test/scala/com/wavesplatform/it/MatcherSuiteBase.scala
dex-it/src/test/scala/com/wavesplatform/it/api/ApiExtensions.scala
dex-it/src/test/scala/com/wavesplatform/it/api/MatcherCommand.scala
dex-it/src/test/scala/com/wavesplatform/it/sync/KafkaIssuesTestSuite.scala
dex-it/src/test/scala/com/wavesplatform/it/sync/MultipleMatcherVersionsTestSuite.scala
dex-it/src/test/scala/com/wavesplatform/it/sync/MultipleMatchersTestSuite.scala
dex-it/src/test/scala/com/wavesplatform/it/sync/networking/DexClientFaultToleranceTestSuite.scala
dex-it/src/test/scala/com/wavesplatform/it/sync/networking/NetworkIssuesTestSuite.scala
project/ItTestPlugin.scala

Build:
* Added SCALATEST_INCLUDE_TAGS to specify "-n" for scalatest;
Test API:
* DexMultipleVersions attribute to mark tests those run againsT multiple different versions of DEX and NODE;
* MultipleMatcherVersionsTestSuite is new test that marked as DexMultipleVersions;
* HasKafka to have a dockerized Kafka setup

DEX-634 Test kit improvements

---

dex/src/main/scala/com/wavesplatform/dex/WavesDexCli.scala
dex/src/main/scala/com/wavesplatform/dex/tool/Checker.scala
dex/src/main/scala/com/wavesplatform/dex/tool/connectors/Connector.scala
dex/src/main/scala/com/wavesplatform/dex/tool/connectors/DexExtensionGrpcConnector.scala
dex/src/main/scala/com/wavesplatform/dex/tool/connectors/DexGrpcConnector.scala
dex/src/main/scala/com/wavesplatform/dex/tool/connectors/DexRestConnector.scala
dex/src/main/scala/com/wavesplatform/dex/tool/connectors/NodeRestConnector.scala
dex/src/main/scala/com/wavesplatform/dex/tool/connectors/RestConnector.scala
dex/src/main/scala/com/wavesplatform/dex/tool/connectors/SuperConnector.scala
dex/src/main/scala/com/wavesplatform/dex/tool/package.scala
dex/src/main/scala/com/wavesplatform/dex/util/ApplicationStopReason.scala
project/Dependencies.scala

Checker for testing DEX state after update via Waves DEX CLI `check-server` command
Concept:
* There are two main components:
1. SuperConnector, is used for connection to REST/gRPC/... APIs of DEX/Node. Can be easily enriched by another connectors. Currently it includes few connectors: `DexRestConnector`, `NodeRestConnector` and `DexExtensionGrpcConnector`;
2. Checker, contains logic of DEX state testing by means of superConnector methods and own ones
* Creation of the SuperConnector and checks are written in fail-fast, pretty FP style;
* All REST methods of connectors are basically the same as in IT module. Main difference is that in this tool we don't parse received Jsons into domain entities and use these Jsons as is;
This tool was tested with the docker containers from IT module

DEX-737 Checker

---

dex-it-common/src/main/scala/com/wavesplatform/dex/it/api/MultipleVersions.scala
dex-it-common/src/main/scala/com/wavesplatform/dex/it/docker/BaseContainer.scala
dex-it-common/src/main/scala/com/wavesplatform/dex/it/docker/DexContainer.scala
dex-it/src/test/java/com/wavesplatform/it/tags/DexItKafkaRequired.java
dex-it/src/test/java/com/wavesplatform/it/tags/DexMultipleVersions.java
dex-it/src/test/java/com/wavesplatform/it/tags/NetworkTests.java
dex-it/src/test/scala/com/wavesplatform/it/it.scala
dex-it/src/test/scala/com/wavesplatform/it/sync/compat/BackwardCompatSuiteBase.scala
dex-it/src/test/scala/com/wavesplatform/it/sync/compat/BackwardCompatTestSuite.scala
dex-it/src/test/scala/com/wavesplatform/it/sync/compat/DatabaseBackwardCompatTestSuite.scala
dex-it/src/test/scala/com/wavesplatform/it/sync/compat/OrderBookBackwardCompatTestSuite.scala

Integration tests:
* Added DatabaseBackwardCompatTestSuite;
* The common part for backward compat tests of MultipleDifferentMatchersTestSuite is separated to BackwardCompatSuiteBase;
* MultipleDifferentMatchersTestSuite is renamed to OrderBookBackwardCompatTestSuite;
Test API:
* Annotations: removed Target=ElementType.METHOD;
* BaseContainer: fixed a bug with printing debug messages when a container wasn't started;

DEX-637 Backward compatibility tests for database

---

dex/src/main/scala/com/wavesplatform/dex/AddressActor.scala
dex/src/main/scala/com/wavesplatform/dex/AddressDirectory.scala
dex/src/main/scala/com/wavesplatform/dex/SpendableBalancesActor.scala
dex/src/test/scala/com/wavesplatform/dex/AddressActorSpecification.scala
dex/src/test/scala/com/wavesplatform/dex/SpendableBalancesActorSpecification.scala

* AddressActor.Command.CancelNotEnoughCoinsOrders renamed to AddressActor.Message.BalanceChanged
* BalanceChanged contains all changes and changes for audit (all changes can be used in future)
* AddressDirectory ignores BalanceChanges message if there isn't any child with specified address
* AddressActor uses decreasing balance changes to cancel orders and all changes for WS extension
* SpendableBalancesActor updates map incompleteStateChanges by only clean changes (unknown so far)

DEX-748 Balance changes optimization

---

dex-it-common/src/main/scala/com/wavesplatform/dex/it/api/websockets/HasWebSockets.scala
dex-it/src/test/scala/com/wavesplatform/it/WsSuiteBase.scala
dex-it/src/test/scala/com/wavesplatform/it/sync/api/ws/WsAddressStreamTestSuite.scala
dex-it/src/test/scala/com/wavesplatform/it/sync/api/ws/WsOrderBookStreamTestSuite.scala
dex-it/src/test/scala/com/wavesplatform/it/sync/api/ws/WsPingPongTestSuite.scala
dex/src/main/scala/com/wavesplatform/dex/WavesDexCli.scala
dex/src/main/scala/com/wavesplatform/dex/api/websockets/connection/TestWsHandlerActor.scala
dex/src/main/scala/com/wavesplatform/dex/api/websockets/connection/WsConnection.scala
dex/src/main/scala/com/wavesplatform/dex/api/websockets/connection/WsConnectionOps.scala
dex/src/main/scala/com/wavesplatform/dex/auth/JwtUtils.scala
dex/src/main/scala/com/wavesplatform/dex/tool/Checker.scala
dex/src/main/scala/com/wavesplatform/dex/tool/connectors/AuthServiceRestConnector.scala
dex/src/main/scala/com/wavesplatform/dex/tool/connectors/Connector.scala
dex/src/main/scala/com/wavesplatform/dex/tool/connectors/DexExtensionGrpcConnector.scala
dex/src/main/scala/com/wavesplatform/dex/tool/connectors/DexRestConnector.scala
dex/src/main/scala/com/wavesplatform/dex/tool/connectors/DexWsConnector.scala
dex/src/main/scala/com/wavesplatform/dex/tool/connectors/RestConnector.scala
dex/src/main/scala/com/wavesplatform/dex/tool/connectors/SuperConnector.scala
dex/src/main/scala/com/wavesplatform/dex/tool/package.scala

Main:
* DexWsConnector and AuthServiceRestConnector introduced
* During initialization SuperConnector establishes connection to:
- DEX WS API and awaits WsInitial message
- Auth Service REST API and tries to load swagger UI page
* Check of the order book WS stream added
* Check of the account updates WS stream added. If Auth Service REST API uri was not specified, Checker skips account updates check
* Checker can test account updates for the specified seed
Miscellaneous:
* WsConnection, WsConnectionOps, TestWsHandlerActor moved to dex module
* Full WS uri passed to WsConnection (prefix is set from outside)
* repeatRequest and repeatRequestOptions moved from RestConnector to Connector

DEX-751 WS API check

---

dex-it-common/src/main/scala/com/wavesplatform/dex/it/dex/DexApi.scala
dex-it/src/test/scala/com/wavesplatform/it/sync/MatcherTestSuite.scala
dex/src/main/scala/com/wavesplatform/dex/AddressActor.scala
dex/src/main/scala/com/wavesplatform/dex/api/MatcherApiRoute.scala
dex/src/main/scala/com/wavesplatform/dex/db/OrderDB.scala
dex/src/test/scala/com/wavesplatform/dex/api/MatcherApiRouteSpec.scala
dex/src/test/scala/com/wavesplatform/dex/db/EmptyOrderDB.scala
dex/src/test/scala/com/wavesplatform/dex/db/TestOrderDB.scala

* MatcherApiRoute new methods:
1. getOrderStatusInfoByIdWithApiKey. It obtains order status info without users's signature;
2. getOrderStatusInfoByIdWithSignature
* AddressActor.Query.GetOrderStatusInfo introduced
* OrderDB getOrderInfo method introduced
* Unit and integration test added

DEX-755 Order Status Info

---

dex/src/main/scala/com/wavesplatform/dex/WavesDexCli.scala
dex/src/main/scala/com/wavesplatform/dex/api/MatcherApiRoute.scala
dex/src/main/scala/com/wavesplatform/dex/tool/Checker.scala
dex/src/main/scala/com/wavesplatform/dex/tool/connectors/AuthServiceRestConnector.scala
dex/src/main/scala/com/wavesplatform/dex/tool/connectors/Connector.scala
dex/src/main/scala/com/wavesplatform/dex/tool/connectors/DexExtensionGrpcConnector.scala
dex/src/main/scala/com/wavesplatform/dex/tool/connectors/DexRestConnector.scala
dex/src/main/scala/com/wavesplatform/dex/tool/connectors/DexWsConnector.scala
dex/src/main/scala/com/wavesplatform/dex/tool/connectors/NodeRestConnector.scala
dex/src/main/scala/com/wavesplatform/dex/tool/connectors/RestConnector.scala
dex/src/main/scala/com/wavesplatform/dex/tool/connectors/SuperConnector.scala
dex/src/main/scala/com/wavesplatform/dex/tool/package.scala

* Stack traces in error messages
* Matcher version in REST API endpoint
* Checker retrieves version from REST API method
* Time between blocks parameter introduced
* RepeatRequestOptions moved to Connector. Now its passed as implicit parameter into repeatRequest method
* Correct scheme for WS API

DEX-766 Checker Improvement

---

waves-integration/src/main/scala/com/wavesplatform/dex/grpc/integration/caches/BlockchainCache.scala
waves-integration/src/test/scala/com/wavesplatform/dex/grpc/integration/caches/BlockchainCacheSpecification.scala

* Cached thread pool driven execution context is used
* Thread sleep in future wrapped by blocking

DEX-745 BlockchainCacheSpecification stabilization

---

dex/src/main/scala/com/wavesplatform/dex/AddressActor.scala
dex/src/main/scala/com/wavesplatform/dex/AddressWsMutableState.scala

* Fixed bug when two error messages are produced for sender of duplicated orders
* Order is removed from active ones during handling of StoreFailed event only if there was pending command for this order

DEX-785 Active orders removing during Kafka issues

---

dex-it-common/src/main/scala/com/wavesplatform/dex/it/api/HasKafka.scala
dex-it-common/src/main/scala/com/wavesplatform/dex/it/test/InformativeTestStart.scala
dex-it/src/test/java/com/wavesplatform/it/tags/DexItExternalKafkaRequired.java
dex-it/src/test/resources/dex-servers/dex-base.conf
dex-it/src/test/scala/com/wavesplatform/it/api/ApiExtensions.scala
dex-it/src/test/scala/com/wavesplatform/it/it.scala
dex-it/src/test/scala/com/wavesplatform/it/sync/KafkaIssuesTestSuite.scala
dex-it/src/test/scala/com/wavesplatform/it/sync/MultipleMatchersTestSuite.scala
dex-it/src/test/scala/com/wavesplatform/it/sync/api/ws/WsPingPongTestSuite.scala
dex-it/src/test/scala/com/wavesplatform/it/sync/compat/OrderBookBackwardCompatTestSuite.scala
dex-it/src/test/scala/com/wavesplatform/it/sync/networking/MultipleMatchersOrderCancelTestSuite.scala
dex/src/main/resources/application.conf
dex/src/main/scala/com/wavesplatform/dex/AddressActor.scala
dex/src/main/scala/com/wavesplatform/dex/Matcher.scala
dex/src/main/scala/com/wavesplatform/dex/api/MatcherApiRoute.scala
dex/src/main/scala/com/wavesplatform/dex/market/AggregatedOrderBookActor.scala
dex/src/main/scala/com/wavesplatform/dex/model/OrderBook.scala
dex/src/main/scala/com/wavesplatform/dex/queue/KafkaMatcherQueue.scala
dex/src/main/scala/com/wavesplatform/dex/settings/EventsQueueSettings.scala
dex/src/test/scala/com/wavesplatform/dex/model/OrderBookSpec.scala
dex/src/test/scala/com/wavesplatform/dex/settings/BaseSettingsSpecification.scala
dex/src/test/scala/com/wavesplatform/dex/settings/MatcherSettingsSpecification.scala
project/Dependencies.scala

Fixed a potential bug with doubled orders:
* Changed semantics to At Most Once;
* Introduced a circuit breaker behind the queue;
* Added failedPlacements to AddressActor (see comments);
Fixed other bugs: 
* Orders those is cancelling doesn't cancel again;
* Ignore cancelling orders during low balance cancels.
Other:
* Little readability improvements.
Tests:
* Added new property based tests for OrderBook;
* MultipleMatchersOrderCancelTestSuite now is correct;
* Improved KafkaIssuesTestSuite, now it is correct.

DEX-789 Better error handling due Kafka issues

---

dex/src/main/scala/com/wavesplatform/dex/cli/WavesDexCli.scala
dex/src/main/scala/com/wavesplatform/dex/tool/Checker.scala
dex/src/main/scala/com/wavesplatform/dex/tool/connectors/AuthServiceRestConnector.scala
dex/src/main/scala/com/wavesplatform/dex/tool/connectors/NodeRestConnector.scala
dex/src/main/scala/com/wavesplatform/dex/tool/connectors/RestConnector.scala
dex/src/main/scala/com/wavesplatform/dex/tool/connectors/SuperConnector.scala

* Time between blocks calculated automatically and used in repeatRequestOptions
* DEX REST API optional parameter introduced. It affects DEX WS API uri
* Node REST API parameter is optional now
* Used seed for address stream test printed
* Checker doesn't check swagger pages

DEX-776 Checker improvements

---

dex-it-common/src/main/scala/com/wavesplatform/dex/it/api/websockets/HasWebSockets.scala
dex-it-common/src/main/scala/com/wavesplatform/dex/it/docker/WavesNodeContainer.scala
dex-it/src/test/scala/com/wavesplatform/it/sync/api/ws/WsAddressStreamTestSuite.scala
dex-it/src/test/scala/com/wavesplatform/it/sync/api/ws/WsOrderBookStreamTestSuite.scala
dex/src/main/scala/com/wavesplatform/dex/AddressActor.scala
dex/src/main/scala/com/wavesplatform/dex/AddressWsMutableState.scala
dex/src/main/scala/com/wavesplatform/dex/SpendableBalancesActor.scala
dex/src/main/scala/com/wavesplatform/dex/market/AggregatedOrderBookActor.scala
dex/src/test/scala/com/wavesplatform/dex/AddressActorSpecification.scala
dex/src/test/scala/com/wavesplatform/dex/SpendableBalancesActorSpecification.scala
waves-ext/src/main/scala/com/wavesplatform/dex/grpc/integration/services/WavesBlockchainApiGrpcService.scala

A possible fix for invalid balances. The situation wasn't reproduced.
Also contains bug fixes:
* Connections with subscriptions to the address's changes can affect each other and the last subscription can be cancelled without an user's will;
* Negative balances can be propagated to the client;
* Changed assets should not be forgotten during new subscriptions. So their changes will be sent in the next WebSocket tick;
* The full state is set only once during multiple simultaneous connections. Fixes possible issues with the stale balances;
And improvements:
* AddressActor could have multiple WebSocket schedules;

DEX-818 Invalid asset balance on connection

---

dex/src/main/scala/com/wavesplatform/dex/actors/address/AddressActor.scala
project/RunApplicationSettings.scala

* After receiving changes AA accumulates another changes within 100ms and then sends them to the active subscriptions

DEX-825 AddressActor scheduling optimization

---

dex-it-common/src/main/scala/com/wavesplatform/dex/it/config/PredefinedAssets.scala
dex-it/src/test/scala/com/wavesplatform/it/api/ApiExtensions.scala
dex-it/src/test/scala/com/wavesplatform/it/sync/MatcherTestSuite.scala
dex-test-common/src/main/scala/com/wavesplatform/dex/asset/DoubleOps.scala
dex/src/main/scala/com/wavesplatform/dex/model/MatcherModel.scala
dex/src/main/scala/com/wavesplatform/dex/model/OrderBook.scala
dex/src/test/scala/com/wavesplatform/dex/MatcherSpecBase.scala
dex/src/test/scala/com/wavesplatform/dex/model/OrderBookTestSuite.scala

* If OrderExecuted event has executedAmount = 0, then Order Book cancels submitted order and thus ExchangeTransaction with NonPositiveAmount error won't be created. Last trade with 0 amount won't appear

DEX-852 Zero executed amount in Order Book

---

Jenkinsfile.build
Jenkinsfile.tests
Jenkinsfile.tests.kafka
Jenkinsfile.tests.multiple-versions
Jenkinsfile.tests.specified-versions
dex-it-common/src/main/scala/com/wavesplatform/dex/it/api/MultipleVersions.scala
dex-it-common/src/main/scala/com/wavesplatform/dex/it/api/node/HasWavesNode.scala
dex-it-common/src/main/scala/com/wavesplatform/dex/it/config/GenesisConfigGenerator.scala
dex-it-common/src/main/scala/com/wavesplatform/dex/it/dex/HasDex.scala
dex-it-common/src/main/scala/com/wavesplatform/dex/it/docker/DexContainer.scala
dex-it-common/src/main/scala/com/wavesplatform/dex/it/docker/WavesNodeContainer.scala
dex-it/src/test/scala/com/wavesplatform/it/sync/networking/MultipleMatchersOrderCancelTestSuite.scala

Tests:
* Specifying whole tag instead of a version;
Jenkinsfiles changes:
* Removed a hack with pulling images;
* Containers and images are removed in Cleanup stage;
* Each build has Cleanup stage;
* Unit tests are run only in Jenkinsfile.tests;
* Jenkinsfile.tests runs fullCheck instead of quickCheck;
* Pull images stage added to multiple versions and specified versions.

DEX-878 Test improvements

---

dex-it/src/test/resources/dex-servers/dex-base.conf
dex/src/main/resources/application.conf

* Ping interval, pong timeout and connection idle timeout (akka.http.server.idle-timeout) increased
* Checked by websocat, dark web socket terminal and websocket.org/echo.html

DEX-850 WS API Ping interval increasing

---

dex-it/src/test/scala/com/wavesplatform/it/sync/RatesTestSuite.scala
dex-it/src/test/scala/com/wavesplatform/it/sync/orders/OrderDynamicFeeTestSuite.scala
dex/src/main/scala/com/wavesplatform/dex/caches/DropOldestFixedBuffer2.scala
dex/src/main/scala/com/wavesplatform/dex/caches/RateCache.scala
dex/src/main/scala/com/wavesplatform/dex/db/RateDB.scala
dex/src/test/scala/com/wavesplatform/dex/caches/DropOldestFixedBuffer2Spec.scala
dex/src/test/scala/com/wavesplatform/dex/model/OrderValidatorSpecification.scala

* RateCache explicitly depends on RateDB;
* RateDB has inMem implementation;
* Added unit tests;
* Updated RatesTestSuite.

DEX-959 Accept an order with a previous fee

---

waves-integration/src/main/scala/com/wavesplatform/dex/grpc/integration/clients/domain/WavesBlock.scala
waves-integration/src/main/scala/com/wavesplatform/dex/grpc/integration/clients/domain/WavesChain.scala
waves-integration/src/main/scala/com/wavesplatform/dex/grpc/integration/clients/domain/WavesFork.scala
waves-integration/src/test/scala/com/wavesplatform/dex/grpc/integration/clients/domain/StatusTransitionsTestSuite.scala
waves-integration/src/test/scala/com/wavesplatform/dex/grpc/integration/clients/domain/WavesChainTestSuite.scala
waves-integration/src/test/scala/com/wavesplatform/dex/grpc/integration/clients/domain/WavesForkTestSuite.scala

* Fixed bugs in WavesChain.dropDifference;
* WavesChain.dropDifference now can work with micro blocks too;
* WavesFork.withBlock:
* Don't resolve the fork if we receive a known micro block, thus we can follow up the original chain;
* doesn't resolve by a full block, a micro block is required now.
Tests:
* StatusTransitionsTestSuite fixed same ids of two different blocks;
* WavesChainTestSuite more tests for dropDifference;
* Added a basic unit tests for WavesFork.

DEX-1010 Moving common block

---

waves-integration/src/main/scala/com/wavesplatform/dex/grpc/integration/clients/blockchainupdates/BlockchainUpdatesConversions.scala
waves-integration/src/main/scala/com/wavesplatform/dex/grpc/integration/clients/blockchainupdates/GrpcBlockchainUpdatesControlledStream.scala
waves-integration/src/main/scala/com/wavesplatform/dex/grpc/integration/clients/combined/CombinedStream.scala
waves-integration/src/main/scala/com/wavesplatform/dex/grpc/integration/clients/combined/CombinedWavesBlockchainClient.scala
waves-integration/src/main/scala/com/wavesplatform/dex/grpc/integration/clients/domain/BlockchainStatus.scala
waves-integration/src/main/scala/com/wavesplatform/dex/grpc/integration/clients/domain/StatusTransitions.scala
waves-integration/src/main/scala/com/wavesplatform/dex/grpc/integration/clients/domain/StatusUpdate.scala
waves-integration/src/main/scala/com/wavesplatform/dex/grpc/integration/clients/domain/UtxUpdate.scala
waves-integration/src/main/scala/com/wavesplatform/dex/grpc/integration/clients/domain/WavesBlock.scala
waves-integration/src/main/scala/com/wavesplatform/dex/grpc/integration/clients/domain/WavesChain.scala
waves-integration/src/main/scala/com/wavesplatform/dex/grpc/integration/clients/domain/WavesFork.scala
waves-integration/src/main/scala/com/wavesplatform/dex/grpc/integration/clients/domain/WavesNodeEvent.scala
waves-integration/src/main/scala/com/wavesplatform/dex/grpc/integration/clients/domain/portfolio/LookAheadPessimisticPortfolios.scala
waves-integration/src/main/scala/com/wavesplatform/dex/grpc/integration/clients/domain/portfolio/SynchronizedPessimisticPortfolios.scala
waves-integration/src/main/scala/com/wavesplatform/dex/grpc/integration/clients/matcherext/GrpcUtxEventsControlledStream.scala
waves-integration/src/test/scala/com/wavesplatform/dex/WavesIntegrationSuiteBase.scala
waves-integration/src/test/scala/com/wavesplatform/dex/grpc/integration/clients/combined/CombinedStreamTestSuite.scala
waves-integration/src/test/scala/com/wavesplatform/dex/grpc/integration/clients/domain/StatusTransitionsTestSuite.scala
waves-integration/src/test/scala/com/wavesplatform/dex/grpc/integration/clients/domain/WavesChainTestSuite.scala
waves-integration/src/test/scala/com/wavesplatform/dex/grpc/integration/clients/domain/WavesForkTestSuite.scala
waves-integration/src/test/scala/com/wavesplatform/dex/grpc/integration/clients/domain/portfolio/LookAheadPessimisticPortfoliosTestSuite.scala
waves-integration/src/test/scala/com/wavesplatform/dex/grpc/integration/clients/domain/portfolio/PessimisticPortfoliosTestSuiteBase.scala

* Added UtxUpdate to collect and combine changes from UTX stream and then apply them to PessimisticPortfolio;
* WavesBlock contains forged transactions' ids;
* WavesFork:
* Status.Resolved contains lost and forged transactions' ids;
* Transactions diffs calculated during resolving;
* Updated StatusTransitions: TransientResolving now reacts on Utx* events correctly;
* CombinedStream: better streams merging;
* GrpcUtxEventsControlledStream.internalSystemStream: BecameReady happens after the first message, see comments for more details.

DEX-1004 Replace transactions in PessimisticPortfolio on reconnect

---

dex-it/src/test/scala/com/wavesplatform/it/MatcherSuiteBase.scala
dex-it/src/test/scala/com/wavesplatform/it/sync/AutoCancelOrderTestSuite.scala
dex-it/src/test/scala/com/wavesplatform/it/sync/BroadcastUntilConfirmedTestSuite.scala
dex/src/main/scala/com/wavesplatform/dex/actors/address/AddressActor.scala
dex/src/main/scala/com/wavesplatform/dex/actors/events/OrderEventsActorState.scala
waves-ext/build.sbt
waves-ext/src/main/scala/com/wavesplatform/dex/grpc/integration/protobuf/WavesToPbConversions.scala
waves-integration/src/main/scala/com/wavesplatform/dex/grpc/integration/clients/combined/CombinedWavesBlockchainClient.scala

* Fixed the issue;
* Removed grpc-server from debianPackageConflicts, because now it is required;
* Stabilized tests;
* Improved checks in AutoCancelOrderTestSuite.

DEX-1047 Orders may be canceled when queue is Kafka

---

.gitignore
.sbtopts
dex/src/main/scala/com/wavesplatform/dex/actors/events/OrderEventsCoordinatorActor.scala
dex/src/main/scala/com/wavesplatform/dex/actors/events/OrderEventsCoordinatorActorState.scala
dex/src/main/scala/com/wavesplatform/dex/actors/events/PendingAddress.scala
dex/src/main/scala/com/wavesplatform/dex/model/ExchangeTransactionCreator.scala
dex/src/main/scala/com/wavesplatform/dex/model/MatcherModel.scala
dex/src/test/scala/com/wavesplatform/dex/actors/events/Generators.scala
dex/src/test/scala/com/wavesplatform/dex/actors/events/OrderEventsCoordinatorActorStateSpec.scala
dex/src/test/scala/com/wavesplatform/dex/actors/events/PendingAddressSpec.scala
dex/src/test/scala/com/wavesplatform/dex/model/ExchangeTransactionCreatorSpecification.scala
dex/src/test/scala/com/wavesplatform/dex/test/WavesEntitiesGen.scala
waves-integration/src/main/scala/com/wavesplatform/dex/fp/MapImplicits.scala
waves-integration/src/main/scala/com/wavesplatform/dex/grpc/integration/clients/domain/BlockchainBalance.scala

* OrderEventsActorState renamed to OrderEventsCoordinatorActorState;
* OrderEventsCoordinatorActorState doesn't pass empty balances (see withBalanceUpdates, withKnownOnNode);
* OrderEventsCoordinatorActorState.withKnownOnNode processes balances even the transaction was processed before;
* Added a documentation to OrderEventsCoordinatorActorState;
* Added tests for OrderEventsCoordinatorActorState and PendingAddress.
Other:
* Added records to .gitignore to support scala-metals.

DEX-1041 Cover OrderEventsCoordinator state

---

dex/src/main/resources/application.conf
dex/src/main/scala/com/wavesplatform/dex/Application.scala
dex/src/main/scala/com/wavesplatform/dex/actors/tx/WriteExchangeTransactionActor.scala
dex/src/main/scala/com/wavesplatform/dex/db/ExchangeTxStorage.scala
dex/src/main/scala/com/wavesplatform/dex/db/leveldb/AsyncLevelDB.scala
dex/src/main/scala/com/wavesplatform/dex/db/leveldb/ReadWriteDB.scala
dex/src/main/scala/com/wavesplatform/dex/db/leveldb/package.scala
dex/src/test/scala/com/wavesplatform/dex/api/http/routes/MatcherApiRouteSpec.scala

* WriteExchangeTransactionActor writes transactions through ExchangeTxStorage;
* Added AsyncLevelDB to migrate to asynchronous work with LevelDB. It uses a separate thread pool.

DEX-1073 Async WriteExchangeTransactionActor

---

dex-it-common/src/main/scala/com/wavesplatform/dex/it/api/HasToxiProxy.scala
dex-it-common/src/main/scala/com/wavesplatform/dex/it/api/MultipleVersions.scala
dex-it-common/src/main/scala/com/wavesplatform/dex/it/test/InformativeTestStart.scala
dex-it/src/test/scala/com/wavesplatform/it/sync/networking/DexClientFaultToleranceTestSuite.scala
dex-it/src/test/scala/com/wavesplatform/it/sync/networking/NetworkIssuesTestSuite.scala
dex/src/main/resources/application.conf
dex/src/main/scala/com/wavesplatform/dex/actors/orderbook/OrderBookActor.scala
dex/src/package/doc/logback.xml
project/Dependencies.scala
waves-ext/src/main/scala/com/wavesplatform/dex/grpc/integration/DEXExtension.scala
waves-integration-it/src/test/resources/logback-test.xml
waves-integration-it/src/test/scala/com/wavesplatform/dex/grpc/integration/IntegrationSuiteBase.scala
waves-integration-it/src/test/scala/com/wavesplatform/dex/grpc/integration/clients/BlockchainUpdatesClientTestSuite.scala
waves-integration-it/src/test/scala/com/wavesplatform/dex/grpc/integration/clients/CombinedWavesBlockchainClientTestSuite.scala
waves-integration/src/main/scala/com/wavesplatform/dex/grpc/integration/clients/blockchainupdates/GrpcBlockchainUpdatesControlledStream.scala
waves-integration/src/main/scala/com/wavesplatform/dex/grpc/integration/clients/combined/CombinedStream.scala
waves-integration/src/main/scala/com/wavesplatform/dex/grpc/integration/clients/combined/CombinedWavesBlockchainClient.scala
waves-integration/src/main/scala/com/wavesplatform/dex/grpc/integration/clients/domain/BlockRef.scala
waves-integration/src/main/scala/com/wavesplatform/dex/grpc/integration/clients/domain/BlockchainBalance.scala
waves-integration/src/main/scala/com/wavesplatform/dex/grpc/integration/clients/domain/WavesBlock.scala
waves-integration/src/main/scala/com/wavesplatform/dex/grpc/integration/clients/domain/WavesChain.scala
waves-integration/src/main/scala/com/wavesplatform/dex/grpc/integration/clients/matcherext/GrpcUtxEventsControlledStream.scala
waves-integration/src/main/scala/com/wavesplatform/dex/grpc/integration/settings/GrpcClientSettings.scala
waves-integration/src/main/scala/com/wavesplatform/dex/grpc/observers/IntegrationObserver.scala
waves-integration/src/test/scala/com/wavesplatform/dex/grpc/integration/clients/domain/WavesForkTestSuite.scala
waves-integration/src/test/scala/com/wavesplatform/dex/grpc/observers/IntegrationObserverSpec.scala

Configuration: tuned keep-alive-time and idle-timeout of gRPC settings. See application.conf for more information;
Dependencies: updated grpc-netty dependency.
gRPC: temporarily disabled metrics and tracing.
Unit tests: IntegrationObserverSpec: added invariant tests.
Integration tests: BlockchainUpdatesClientTestSuite and CombinedWavesBlockchainClientTestSuite contains tests with simulation of network issues.

DEX-1084 Wrong balances debugging

---

dex-it/src/test/scala/com/wavesplatform/it/sync/api/ws/WsAddressStreamTestSuite.scala
dex/src/main/resources/application.conf
waves-integration-it/src/test/scala/com/wavesplatform/dex/grpc/integration/clients/BlockchainUpdatesClientTestSuite.scala
waves-integration-it/src/test/scala/com/wavesplatform/dex/grpc/integration/clients/CombinedWavesBlockchainClientTestSuite.scala
waves-integration/src/main/scala/com/wavesplatform/dex/grpc/integration/clients/blockchainupdates/GrpcBlockchainUpdatesControlledStream.scala
waves-integration/src/main/scala/com/wavesplatform/dex/grpc/integration/clients/combined/CombinedStream.scala
waves-integration/src/main/scala/com/wavesplatform/dex/grpc/integration/clients/combined/CombinedWavesBlockchainClient.scala
waves-integration/src/main/scala/com/wavesplatform/dex/grpc/integration/clients/domain/StatusTransitions.scala
waves-integration/src/main/scala/com/wavesplatform/dex/grpc/integration/clients/domain/StatusUpdate.scala
waves-integration/src/main/scala/com/wavesplatform/dex/grpc/integration/clients/domain/WavesChain.scala
waves-integration/src/main/scala/com/wavesplatform/dex/grpc/integration/clients/domain/WavesFork.scala
waves-integration/src/test/scala/com/wavesplatform/dex/WavesIntegrationSuiteBase.scala
waves-integration/src/test/scala/com/wavesplatform/dex/grpc/integration/clients/combined/CombinedStreamTestSuite.scala
waves-integration/src/test/scala/com/wavesplatform/dex/grpc/integration/clients/domain/StatusTransitionsTestSuite.scala
waves-integration/src/test/scala/com/wavesplatform/dex/grpc/integration/clients/domain/WavesChainTestSuite.scala
waves-integration/src/test/scala/com/wavesplatform/dex/grpc/integration/clients/domain/WavesForkTestSuite.scala

Solution for an excess blocks removing during stream issues.
Configuration: 
* Updated keep-alive-time documentation and the default value;
* max-cached-latest-block-updates includes micro blocks.
Code:
* WavesChain:
* checks the height even if there is no history;
* withoutLastLiquidOrFull is removed, because is not used anymore;
* dropAfter now ignores a situation when the height is higher than of chain. Added tests for it; 
* CombinedStream contains a better recovery logic, see comments;
* StatusTransitions:
* requires a restart when we failed to apply a new block to the empty chain
* updates height always when apply a block or a micro block.
Tests: 
* Added new tests;
* Stabilized WsAddressStreamTestSuite, fixed the connection cut logic.
Other: improved logs.

DEX-1087 WavesChain failed invariant

---

dex-it-common/src/main/scala/com/wavesplatform/dex/it/api/dex/DexApiSyntax.scala
dex-it-common/src/main/scala/com/wavesplatform/dex/it/docker/DexContainer.scala
dex-it/src/test/scala/com/wavesplatform/it/api/ApiExtensions.scala
dex-it/src/test/scala/com/wavesplatform/it/sync/MarketOrderTestSuite.scala
dex-it/src/test/scala/com/wavesplatform/it/sync/compat/DatabaseBackwardCompatTestSuite.scala
dex-it/src/test/scala/com/wavesplatform/it/sync/orders/MakerTakerFeeTestSuite.scala
dex-it/src/test/scala/com/wavesplatform/it/sync/orders/OrderDynamicFeeTestSuite.scala
dex-it/src/test/scala/com/wavesplatform/it/sync/orders/OrderFixedFeeTestSuite.scala

Now we save snapshots before restart Matcher with a new configuration, that affects matching.

DEX-1146 OrderDynamicFeeTestSuite failed

---

dex-it/src/test/scala/com/wavesplatform/it/sync/networking/DexClientFaultToleranceTestSuite.scala
jenkins/tests.Jenkinsfile
waves-ext/src/main/resources/application.conf

- turned off tracing for tests in Jenkins (they didn't work, only spawned errors in logs)
- fixed waves-ext config
- added comment about DexClientFaultToleranceTestSuite - we'll wait node version 1.3.7 for possible fix

DEX-1337 small fixes
