build.sbt, dex-it/src/test/scala/com/wavesplatform/it/sync/RatesTestSuite.scala, dex/src/main/scala/com/wavesplatform/dex/Matcher.scala, dex/src/main/scala/com/wavesplatform/dex/api/MatcherApiRouteV1.scala, dex/src/main/scala/com/wavesplatform/dex/api/OrderBookSnapshotHttpCache.scala, dex/src/main/scala/com/wavesplatform/dex/model/AssetDecimalsCache.scala, dex/src/main/scala/com/wavesplatform/dex/model/MatcherModel.scala, dex/src/main/scala/com/wavesplatform/dex/model/OrderBookResult.scala, dex/src/test/scala/com/wavesplatform/dex/api/MatcherApiRouteSpec.scala, dex/src/test/scala/com/wavesplatform/dex/api/OrderBookSnapshotHttpCacheSpec.scala
Also LimitOrder.feeAsset contains right fee asset. Fixed RatesTestSuite.
=> DEX-329 Orderbook API V1

dex/src/main/scala/com/wavesplatform/dex/Matcher.scala, dex/src/main/scala/com/wavesplatform/dex/history/HistoryRouter.scala, dex/src/main/scala/com/wavesplatform/dex/model/AssetDecimalsCache.scala, dex/src/main/scala/com/wavesplatform/dex/model/MatcherModel.scala, project/ExtensionPackaging.scala
* Added logs and a default values to catch assets absence;
* "Package" and "Source" in deb info now correct and doesn't contain a node version;
=> DEX-345 Can not start DEX

README.md, dex/src/main/scala/com/wavesplatform/dex/api/MatcherApiRoute.scala, dex/src/main/scala/com/wavesplatform/dex/api/MatcherResponse.scala, dex/src/main/scala/com/wavesplatform/dex/error/MatcherError.scala, project/Dependencies.scala
* akka-stream-kafka updated to 1.0.4;
=> DEX-332 Better AskTimeoutException detection

dex/src/main/scala/com/wavesplatform/dex/MatcherTool.scala, dex/src/main/scala/com/wavesplatform/dex/model/OrderInfo.scala
* forceWrite the batch at end;
* deleting wrong order infos;
Wrong orders are shown in logs:
> Can't parse the <Order id here> order: <descriptiom>, will remove it
=> DEX-362 OrderInfo migration errors

build.sbt, dex-it/src/test/scala/com/wavesplatform/it/sync/smartcontracts/OrderTypeTestSuite.scala, dex-it/src/test/scala/com/wavesplatform/it/sync/smartcontracts/OrdersFromScriptedAssetTestSuite.scala, dex/src/main/scala/com/wavesplatform/dex/api/MatcherApiRoute.scala, dex/src/main/scala/com/wavesplatform/dex/api/MatcherResponse.scala, dex/src/main/scala/com/wavesplatform/dex/smart/MatcherContext.scala, dex/src/test/scala/com/wavesplatform/dex/api/MatcherApiRouteSpec.scala, project/ExtensionPackaging.scala
* Fixed an incompatibility with Node;
* Exact NODE's version dependency;
=> DEX-356 Release 1.0.1

.travis.yml, dex-it/src/test/scala/com/wavesplatform/it/api/AsyncMatcherHttpApi.scala, dex-it/src/test/scala/com/wavesplatform/it/api/SyncMatcherHttpApi.scala, dex-it/src/test/scala/com/wavesplatform/it/sync/OrderFeeTestSuite.scala, dex-it/src/test/scala/com/wavesplatform/it/sync/RatesTestSuite.scala, dex-it/src/test/scala/com/wavesplatform/it/sync/smartcontracts/ExtraFeeTestSuite.scala, dex/src/test/scala/com/wavesplatform/dex/api/MatcherApiRouteSpec.scala, dex/src/test/scala/com/wavesplatform/dex/settings/MatcherSettingsSpecification.scala
-- added tests for settings and REST handlers
=> DEX-270 Tests for dynamic order-fee mode

.travis.yml, dex-it/src/test/scala/com/wavesplatform/it/sync/MatchingRulesTestSuite.scala, dex/src/main/scala/com/wavesplatform/dex/api/MatcherApiRoute.scala, dex/src/main/scala/com/wavesplatform/dex/model/OrderBook.scala, dex/src/main/scala/com/wavesplatform/dex/settings/MatchingRules.scala, dex/src/test/scala/com/wavesplatform/dex/model/OrderBookSpec.scala
Matchable orders from the different levels now aren't matched
=> DEX-372 Fix of matching orders from different levels (v.1.0.x)

.travis.yml, dex-it/src/test/scala/com/wavesplatform/it/api/AsyncMatcherHttpApi.scala, dex-it/src/test/scala/com/wavesplatform/it/api/SyncMatcherHttpApi.scala, dex-it/src/test/scala/com/wavesplatform/it/it.scala, dex-it/src/test/scala/com/wavesplatform/it/sync/MultipleMatchersTestSuite.scala, dex/src/main/scala/com/wavesplatform/dex/AddressActor.scala, dex/src/main/scala/com/wavesplatform/dex/AddressDirectory.scala, dex/src/main/scala/com/wavesplatform/dex/Matcher.scala, dex/src/main/scala/com/wavesplatform/dex/db/OrderDB.scala, dex/src/main/scala/com/wavesplatform/dex/market/OrderBookActor.scala, dex/src/main/scala/com/wavesplatform/dex/model/MatcherModel.scala, dex/src/test/scala/com/wavesplatform/dex/db/EmptyOrderDB.scala, dex/src/test/scala/com/wavesplatform/dex/db/TestOrderDB.scala, dex/src/test/scala/com/wavesplatform/dex/matching/ReservedBalanceSpecification.scala
* If an OrderBook didn't find the order by id, it sends a Failure response;
* Fixed a resolving of order's cancellation;
* AddressActor catches the OrderCancelFailure response;
* A new integration test;
=> DEX-367 Simultaneous single and group cancels

dex-it/src/test/scala/com/wavesplatform/it/api/AsyncMatcherHttpApi.scala, dex-it/src/test/scala/com/wavesplatform/it/api/SyncMatcherHttpApi.scala, dex-it/src/test/scala/com/wavesplatform/it/sync/OrderHistoryTestSuite.scala, dex-it/src/test/scala/com/wavesplatform/it/sync/config/MatcherPriceAssetConfig.scala, dex/src/main/resources/order-history/order-history-ddl.sql, dex/src/main/scala/com/wavesplatform/dex/history/DBRecords.scala, dex/src/main/scala/com/wavesplatform/dex/history/HistoryRouter.scala, dex/src/main/scala/com/wavesplatform/dex/model/MatcherModel.scala, dex/src/test/scala/com/wavesplatform/dex/AssetPairDecimals.scala, dex/src/test/scala/com/wavesplatform/dex/history/HistoryRouterSpecification.scala
* fee in History Database added; 
* OrderHistoryTestSuite refactoring
=> DEX-402 History Database fee denormalization fix

build.sbt, dex/src/main/scala/com/wavesplatform/dex/Matcher.scala, dex/src/main/scala/com/wavesplatform/dex/model/ExchangeTransactionCreator.scala, dex/src/main/scala/com/wavesplatform/dex/model/OrderValidator.scala, dex/src/test/scala/com/wavesplatform/dex/model/OrderValidatorSpecification.scala
* Calculation of the min order fee now takes into account fee asset decimals;
* Formalization of the orders creation in unit-tests
=> DEX-411 Min order fee fix

dex-it/src/test/scala/com/wavesplatform/it/sync/MatchingRulesTestSuite.scala, dex/src/main/scala/com/wavesplatform/dex/Matcher.scala, dex/src/main/scala/com/wavesplatform/dex/market/OrderBookActor.scala, dex/src/main/scala/com/wavesplatform/dex/settings/MatcherSettings.scala, dex/src/main/scala/com/wavesplatform/dex/settings/MatchingRule.scala, dex/src/test/scala/com/wavesplatform/dex/market/MatcherActorSpecification.scala, dex/src/test/scala/com/wavesplatform/dex/market/OrderBookActorSpecification.scala, dex/src/test/scala/com/wavesplatform/dex/model/DenormalizedMatchingRulesSpecification.scala, dex/src/test/scala/com/wavesplatform/dex/settings/MatcherSettingsSpecification.scala
* actual matching rules for the pair now are updated before order book creation
=> DEX-404 Price level 0 is forbidden for buy orders

dex-it/src/test/scala/com/wavesplatform/it/sync/OrderFeeTestSuite.scala
=> DEX-328 reservedBalance of orderV3 is measuring incorrect

dex-it/src/test/scala/com/wavesplatform/it/api/AsyncMatcherHttpApi.scala, dex-it/src/test/scala/com/wavesplatform/it/api/SyncMatcherHttpApi.scala, dex-it/src/test/scala/com/wavesplatform/it/sync/api/GetOrderBookTestSuite.scala
=> Dex 385 order books configurable depth tests

dex-it/src/test/scala/com/wavesplatform/it/sync/MatchingRulesTestSuite.scala
Added it test for case when tick size was changed and old orders should have posibility to be matched with their visible price
=> DEX-412 old orders matching

dex-it/src/test/scala/com/wavesplatform/it/sync/TradersTestSuite.scala
-- random order version replaced with the loop
-- added tests to check order cancellation after moving all aff fee assets
=> DEX-417 To improve tests of TradersTestSuite

dex-it/src/test/scala/com/wavesplatform/it/sync/OrderHistoryTestSuite.scala
=> DEX-402 History Database fee denormalization

dex-it/src/test/resources/genesis.conf, dex-it/src/test/resources/nodes/waves-1.conf, dex-it/src/test/resources/nodes/waves-2.conf, dex-it/src/test/scala/com/wavesplatform/it/sync/OrderDeviationsTestSuite.scala, dex-it/src/test/scala/com/wavesplatform/it/sync/smartcontracts/OrdersFromScriptedAccTestSuite.scala, dex-it/src/test/scala/com/wavesplatform/it/sync/smartcontracts/OrdersFromScriptedAssetTestSuite.scala, waves-integration-it/src/test/resources/nodes/waves-1.conf, waves-integration-it/src/test/scala/com/wavesplatform/dex/grpc/integration/sync/WavesBlockchainAsyncClientTestSuite.scala
* Fastest start;
* Decreased a microblock interval;
* Fixes for OrderDeviationsTestSuite;
=> DEX-449 Faster integration tests

dex-it/src/test/resources/order-history/init-user-db.sh, dex-it/src/test/scala/com/wavesplatform/it/DockerContainerLauncher.scala, dex-it/src/test/scala/com/wavesplatform/it/sync/OrderDeviationsTestSuite.scala, dex-it/src/test/scala/com/wavesplatform/it/sync/OrderHistoryTestSuite.scala, dex/src/main/resources/application.conf, dex/src/main/scala/com/wavesplatform/dex/settings/PostgresConnection.scala
Also fixed OrderDeviationsTestSuite
=> DEX-471 merge version-1.0.x into master

dex-it/src/test/scala/com/wavesplatform/it/sync/OrderRestrictionsTestSuite.scala, dex/src/main/scala/com/wavesplatform/dex/Matcher.scala, dex/src/main/scala/com/wavesplatform/dex/caches/MatchingRulesCache.scala, dex/src/main/scala/com/wavesplatform/dex/settings/MatchingRule.scala, dex/src/main/scala/com/wavesplatform/dex/settings/OrderRestrictionsSettings.scala
=> DEX-487 Can't get an order book's info

dex-it/src/test/scala/com/wavesplatform/it/api/SyncMatcherHttpApi.scala, dex-it/src/test/scala/com/wavesplatform/it/sync/CancelOrderTestSuite.scala, dex/src/main/scala/com/wavesplatform/dex/AddressActor.scala, dex/src/main/scala/com/wavesplatform/dex/Matcher.scala, dex/src/main/scala/com/wavesplatform/dex/api/MatcherResponse.scala, dex/src/test/scala/com/wavesplatform/dex/matching/ReservedBalanceSpecification.scala
* AddressActor - expirable pending requests
=> DEX-488 Mass cancel issue

dex-it/src/test/scala/com/wavesplatform/it/sync/CancelOrderTestSuite.scala, dex/src/main/scala/com/wavesplatform/dex/AddressActor.scala, dex/src/main/scala/com/wavesplatform/dex/Matcher.scala, dex/src/main/scala/com/wavesplatform/dex/market/CreateExchangeTransactionActor.scala, dex/src/main/scala/com/wavesplatform/dex/market/OrderBookActor.scala, dex/src/test/scala/com/wavesplatform/dex/market/MatcherActorSpecification.scala, dex/src/test/scala/com/wavesplatform/dex/market/OrderBookActorSpecification.scala
* Added CreateExchangeTransactionActor. It listens for events from AddressActor and creates a transactions. An event means that AddressActor observed OrderExecuted;
* OrderBookActor no longer creates transactions;
* AddressActor shows more information about an order canceled during balance checks;
* Added an integration test;
=> DEX-521 Wrong cancel

project/Dependencies.scala, project/Network.scala
* `Version` object introduced
* Unused dependencies removed
=> DEX-528 Dependencies refactoring

dex-it/src/test/scala/com/wavesplatform/it/api/SyncMatcherHttpApi.scala, dex-it/src/test/scala/com/wavesplatform/it/sync/CancelOrderTestSuite.scala, dex-it/src/test/scala/com/wavesplatform/it/sync/MarketOrderTestSuite.scala, dex-it/src/test/scala/com/wavesplatform/it/sync/PostgresHistoryDatabaseTestSuite.scala, dex/src/main/resources/application.conf, dex/src/main/scala/com/wavesplatform/dex/market/ExchangeTransactionBroadcastActor.scala, dex/src/test/scala/com/wavesplatform/dex/market/ExchangeTransactionBroadcastActorSpecification.scala
Catching exceptions in ExchangeTransactionBroadcastActor and retry, if it is possible by mode
=> DEX-530 Exceptions during big block application

dex-it/src/test/resources/logback-test.xml, dex-it/src/test/scala/com/wavesplatform/it/MatcherSuiteBase.scala, dex-it/src/test/scala/com/wavesplatform/it/docker/DexItDocker.scala, dex-it/src/test/scala/com/wavesplatform/it/sync/BroadcastUntilConfirmedTestSuite.scala, dex/src/main/scala/com/wavesplatform/dex/market/MatcherActor.scala, dex/src/package/doc/logback.xml, dex/src/test/resources/logback-verbose.xml, waves-integration-it/src/test/resources/logback-test.xml, waves-integration-it/src/test/resources/logback.xml
* Fixed test suite. We should send requests until NODE will be available;
* Fixed an issue with doubled logs;
* All time in logs now in UTC;
=> DEX-541 Broken BroadcastUntilConfirmedTestSuite

.travis.yml, README.md, dex/src/package/doc/main.conf
* Fixed Travis configuration to work with sbt 1.3.4;
* Fixed a wrong configuration example;
* README.md contains a neutral Linux directory instead of mine :)
=> DEX-545 Travis build issues

dex/src/main/resources/application.conf
Added "connections.max.idle.ms" both to consumer and producer.
=> DEX-549 New integration tests issues

waves-integration/src/main/scala/com/wavesplatform/dex/grpc/integration/DEXExtension.scala, waves-integration/src/main/scala/com/wavesplatform/dex/grpc/integration/clients/WavesBlockchainGrpcAsyncClient.scala
* DEXExtension shuts down without termination awaiting
* Logging of connection loses and restores added
=> DEX-555 Waves extension force shutdown

dex/src/main/scala/com/wavesplatform/dex/AddressActor.scala, dex/src/main/scala/com/wavesplatform/dex/Matcher.scala, dex/src/main/scala/com/wavesplatform/dex/api/MatcherApiRoute.scala, dex/src/main/scala/com/wavesplatform/dex/api/OrderBookSnapshotHttpCache.scala, dex/src/main/scala/com/wavesplatform/dex/market/ExchangeTransactionBroadcastActor.scala, dex/src/main/scala/com/wavesplatform/dex/market/OrderBookActor.scala, dex/src/main/scala/com/wavesplatform/dex/model/OrderValidator.scala, dex/src/main/scala/com/wavesplatform/dex/queue/LocalMatcherQueue.scala, dex/src/main/scala/com/wavesplatform/dex/time/NTP.scala, dex/src/main/scala/com/wavesplatform/dex/time/Time.scala, dex/src/test/scala/com/wavesplatform/NTPTime.scala, dex/src/test/scala/com/wavesplatform/dex/market/ExchangeTransactionBroadcastActorSpecification.scala, dex/src/test/scala/com/wavesplatform/dex/model/OrderHistoryStub.scala, dex/src/test/scala/com/wavesplatform/dex/model/OrderValidatorSpecification.scala, dex/src/test/scala/com/wavesplatform/dex/time/TestTime.scala
* Moved Time and NTP from NODE to DEX;
=> DEX-561 Long NTP init

dex/src/main/scala/com/wavesplatform/dex/Application.scala, dex/src/main/scala/com/wavesplatform/dex/Matcher.scala, dex/src/main/scala/com/wavesplatform/dex/util/ApplicationStopReason.scala, dex/src/main/scala/com/wavesplatform/dex/util/package.scala, dex/src/package/systemd.service
* DEX related stop reasons introduced
* systemd.service contains corrected RestartPreventExitStatus
=> DEX-536 Own force stop application

build.sbt
NODE version is bumped to v1.1.7
=> DEX-585 NODE 1.1.7

dex-it/src/test/scala/com/wavesplatform/it/sync/api/MatcherWebSocketsTestSuite.scala, dex/src/main/scala/com/wavesplatform/dex/Matcher.scala, dex/src/main/scala/com/wavesplatform/dex/api/MatcherWebSocketRoute.scala
* MatcherWebSocketRoute introduced
* Endpoint /ws/time returns current time
=> DEX-565 Basic web socket implementation

dex-it-common/src/main/scala/com/wavesplatform/dex/it/docker/BaseContainer.scala, dex-it-common/src/main/scala/com/wavesplatform/dex/it/docker/DexContainer.scala, dex-it-common/src/main/scala/com/wavesplatform/dex/it/docker/WavesNodeContainer.scala, dex-it-common/src/main/scala/com/wavesplatform/dex/it/waves/MkWavesEntities.scala, dex/src/main/container/start.sh, dex/src/test/scala/com/wavesplatform/dex/MatcherSpecBase.scala, dex/src/test/scala/com/wavesplatform/dex/grpc/integration/clients/WavesBlockchainCachingClientSpecification.scala, waves-ext/build.sbt, waves-ext/src/main/scala/com/wavesplatform/dex/grpc/integration/services/WavesBlockchainApiGrpcService.scala, waves-grpc/src/main/protobuf/waves_blockchain_api.proto, waves-integration-it/src/test/container/start-waves.sh, waves-integration-it/src/test/resources/logback-test.xml, waves-integration-it/src/test/resources/nodes/logback-container.xml, waves-integration-it/src/test/scala/com/wavesplatform/dex/grpc/integration/clients/WavesBlockchainAsyncClientTestSuite.scala, waves-integration/src/main/scala/com/wavesplatform/dex/grpc/integration/WavesBlockchainClientBuilder.scala, waves-integration/src/main/scala/com/wavesplatform/dex/grpc/integration/clients/WavesBlockchainCachingClient.scala, waves-integration/src/main/scala/com/wavesplatform/dex/grpc/integration/clients/WavesBlockchainClient.scala, waves-integration/src/main/scala/com/wavesplatform/dex/grpc/integration/clients/WavesBlockchainGrpcAsyncClient.scala
* `allAssetsSpendableBalance` method introduced (waves_blockchain_api.proto, WavesBlockchainApiGrpcService, WavesBlockchainClient)
* Test start and end labels fixed
=> DEX-593 All assets spendable balance

dex-it/src/test/scala/com/wavesplatform/it/sync/MarketOrderTestSuite.scala, dex/src/main/scala/com/wavesplatform/dex/AddressActor.scala
* getTradableBalance method fixed
* IT test added
=> DEX-621 Market order creation fix

dex/src/package/doc/logback.xml, project/Dependencies.scala
=> DEX-617 Add LoggingEventCompositeJsonEncoder JAR into package

dex/src/main/scala/com/wavesplatform/dex/Matcher.scala, waves-ext/src/main/scala/com/wavesplatform/dex/grpc/integration/services/WavesBlockchainApiGrpcService.scala, waves-grpc/src/main/protobuf/waves_blockchain_api.proto, waves-integration/src/main/scala/com/wavesplatform/dex/grpc/integration/clients/WavesBlockchainCachingClient.scala, waves-integration/src/main/scala/com/wavesplatform/dex/grpc/integration/clients/WavesBlockchainClient.scala, waves-integration/src/main/scala/com/wavesplatform/dex/grpc/integration/clients/WavesBlockchainGrpcAsyncClient.scala
* New gRPC call GetNodeAddress introduced
* During start and after switching of the Nodes DEX logs Node's IP
=> DEX-616 Log IP of a Node

dex-it-common/src/main/scala/com/wavesplatform/dex/it/api/node/NodeApiOps.scala, dex-it/src/test/scala/com/wavesplatform/it/sync/MarketOrderTestSuite.scala, dex-it/src/test/scala/com/wavesplatform/it/sync/TradersTestSuite.scala, dex-it/src/test/scala/com/wavesplatform/it/sync/smartcontracts/OrdersFromScriptedAssetTestSuite.scala, dex/src/main/scala/com/wavesplatform/dex/model/ExchangeTransactionCreator.scala, dex/src/test/scala/com/wavesplatform/dex/model/ExchangeTransactionCreatorSpecification.scala
* ExchangeTransactionV1 is disabled now;
* Fixed MarketOrderTestSuite;
* Fixed TradersTestSuite;
=> DEX-626 Issue only ExchangeTransactionV2

project/ReleasePlugin.scala
=> DEX-589 SHA256 checksums for ZIP archives

dex-it-common/src/main/scala/com/wavesplatform/dex/it/api/websockets/HasWebSockets.scala, dex-it-common/src/main/scala/com/wavesplatform/dex/it/api/websockets/WebSocketConnection.scala, dex-it/src/test/scala/com/wavesplatform/it/sync/api/MatcherWebSocketsTestSuite.scala, dex/src/main/scala/com/wavesplatform/dex/Matcher.scala, dex/src/main/scala/com/wavesplatform/dex/OrderBookWsState.scala, dex/src/main/scala/com/wavesplatform/dex/api/MatcherWebSocketRoute.scala, dex/src/main/scala/com/wavesplatform/dex/api/http/ApiMarshallers.scala, dex/src/main/scala/com/wavesplatform/dex/api/websockets/WsLastTrade.scala, dex/src/main/scala/com/wavesplatform/dex/api/websockets/WsOrderBook.scala, dex/src/main/scala/com/wavesplatform/dex/fp/MayBeEmpty.scala, dex/src/main/scala/com/wavesplatform/dex/json/Implicits.scala, dex/src/main/scala/com/wavesplatform/dex/market/MatcherActor.scala, dex/src/main/scala/com/wavesplatform/dex/market/OrderBookActor.scala, dex/src/main/scala/com/wavesplatform/dex/model/LevelAmounts.scala, dex/src/main/scala/com/wavesplatform/dex/model/OrderBook.scala, dex/src/test/scala/com/wavesplatform/dex/api/websockets/WebSocketMessagesSerdeSpecification.scala, dex/src/test/scala/com/wavesplatform/dex/market/MatcherActorSpecification.scala, dex/src/test/scala/com/wavesplatform/dex/market/OrderBookActorSpecification.scala, dex/src/test/scala/com/wavesplatform/dex/model/OrderBookSpec.scala, dex/src/test/scala/com/wavesplatform/dex/model/OrderBookTestSuite.scala, waves-integration/src/main/scala/com/wavesplatform/dex/domain/model/package.scala, waves-integration/src/main/scala/com/wavesplatform/dex/domain/order/OrderType.scala
WebSocket API: 
* Added the MatcherWebSocketRoute.orderbook route;
* Added web socket entities: WsOrderBookState and WsLastTrade;
MatcherActor:
* Has AddWsSubscription for order books. It forwards such messages to concrete order books;
OrderBookActor:
* Added OrderBookWsState to manage websocket subscriptions and data to send in an order book;
* Implemented the right WebSocket termination;
OrderBook:
* Added LevelAmounts. It is a type alias to represent level changes (or an absolute value) for multiple levels and both sides;
* OrderBook returns LevelAmounts for each action;
JSON:
* json.Implicits.JsPathOps.formatMayBeEmpty to exclude empty objects from JSON;
FP:
* Added the MayBeEmpty type class. It is a trait for objects those could be empty;
Tests:
* WebSocketMessagesSerdeSpecification: …
=> DEX-650 Basic implementation Order Book WebSocket API

dex-it-common/src/main/scala/com/wavesplatform/dex/it/api/websockets/WebSocketAuthenticatedConnection.scala, dex-it-common/src/main/scala/com/wavesplatform/dex/it/api/websockets/WebSocketConnection.scala, dex-test-common/src/main/scala/com/wavesplatform/dex/test/matchers/DiffMatcherWithImplicits.scala, dex/src/main/scala/com/wavesplatform/dex/AddressActor.scala, dex/src/main/scala/com/wavesplatform/dex/AddressWsMutableState.scala, dex/src/test/scala/com/wavesplatform/dex/api/RouteSpec.scala
AddressActor removes subscriber after closing the connection
=> DEX-630 Authenticated stream WS unsubscription

dex-it/src/test/scala/com/wavesplatform/it/sync/PostgresHistoryDatabaseTestSuite.scala, dex/src/main/scala/com/wavesplatform/dex/AddressDirectory.scala
* AddressDirectory isSubmittedFilled condition fixed
* It tests added
=> DEX-644 Save order with rounding issues into Postgres history

dex-it-common/src/main/scala/com/wavesplatform/dex/it/api/websockets/HasWebSockets.scala, dex-it-common/src/main/scala/com/wavesplatform/dex/it/api/websockets/WebSocketAuthenticatedConnection.scala, dex-it-common/src/main/scala/com/wavesplatform/dex/it/api/websockets/WebSocketConnection.scala, dex-it/src/test/scala/com/wavesplatform/it/sync/api/MatcherWebSocketsTestSuite.scala, dex-test-common/src/main/scala/com/wavesplatform/dex/test/matchers/DiffMatcherWithImplicits.scala, dex/src/main/scala/com/wavesplatform/dex/api/websockets/WsAddressState.scala, dex/src/main/scala/com/wavesplatform/dex/api/websockets/WsOrder.scala, dex/src/main/scala/com/wavesplatform/dex/api/websockets/WsOrderBook.scala, dex/src/test/scala/com/wavesplatform/dex/api/websockets/WebSocketMessagesSerdeSpecification.scala
* WsAddressState, WsOrderBook got timestamp
* Diffx implicits that ignore timestamp added
* WebSocketConnection logs any messages
* WebSocketMessagesSerdeSpecification improved
=> DEX-656 Timestamp in web socket messages

dex/src/main/scala/com/wavesplatform/dex/api/MatcherApiRoute.scala, wavesNode.sbt
* Added "networkByte" to JSON of GET /settings;
* NODE updated to 1.1.9;
=> DEX-106 Network byte in REST API

dex-it/src/test/scala/com/wavesplatform/it/sync/MatcherMassOrdersTestSuite.scala, dex-it/src/test/scala/com/wavesplatform/it/sync/RestOrderLimitTestSuite.scala, dex-test-common/src/main/scala/com/wavesplatform/dex/test/matchers/DiffMatcherWithImplicits.scala, dex/src/main/resources/application.conf, dex/src/main/scala/com/wavesplatform/dex/AddressActor.scala, dex/src/main/scala/com/wavesplatform/dex/Matcher.scala, dex/src/main/scala/com/wavesplatform/dex/settings/AddressActorSettings.scala, dex/src/main/scala/com/wavesplatform/dex/settings/MatcherSettings.scala, dex/src/test/scala/com/wavesplatform/dex/settings/BaseSettingsSpecification.scala, dex/src/test/scala/com/wavesplatform/dex/settings/MatcherSettingsSpecification.scala
* AddressActor got dedicated settings section in application.conf
* DiffMatcherWithImplicits enriched with string diff (some unit tests fixes)
=> DEX-678 Address actor dedicated settings

dex-it-common/src/main/scala/com/wavesplatform/dex/it/api/websockets/HasWebSockets.scala, dex-it/src/test/scala/com/wavesplatform/it/sync/api/ws/PingPongTestSuite.scala, dex/src/main/scala/com/wavesplatform/dex/api/MatcherWebSocketRoute.scala
* Connection lifetime is also limited by token (signature) lifetime
* AuthParams introduced
* signedGet returns AuthParams
=> DEX-691 WS connection lifetime restriction

dex-it-common/src/main/scala/com/wavesplatform/dex/it/api/websockets/WsAuthenticatedConnection.scala, dex-it/src/test/scala/com/wavesplatform/it/MatcherSuiteBase.scala, dex-it/src/test/scala/com/wavesplatform/it/api/ApiExtensions.scala, dex-it/src/test/scala/com/wavesplatform/it/sync/api/ws/WebSocketPrivateStreamTestSuite.scala, dex-it/src/test/scala/com/wavesplatform/it/sync/api/ws/WsConnectionTestSuite.scala, dex-it/src/test/scala/com/wavesplatform/it/sync/networking/NetworkIssuesTestSuite.scala, dex/src/main/scala/com/wavesplatform/dex/AddressActor.scala, dex/src/main/scala/com/wavesplatform/dex/AddressWsMutableState.scala, dex/src/main/scala/com/wavesplatform/dex/api/websockets/WsOrder.scala
* Balance changes messages are deduplicated
* Integration tests fixed
* Minor refactoring
=> DEX-687 WS API private stream messages deduplication

dex-it-common/src/main/scala/com/wavesplatform/dex/it/api/websockets/HasWebSockets.scala, dex-it/src/test/scala/com/wavesplatform/it/sync/api/ws/WebSocketPrivateStreamTestSuite.scala, dex-it/src/test/scala/com/wavesplatform/it/sync/api/ws/WsConnectionTestSuite.scala, dex/src/main/scala/com/wavesplatform/dex/api/MatcherWebSocketRoute.scala, dex/src/main/scala/com/wavesplatform/dex/error/MatcherError.scala
* Public key in private streams url was replaced by address. Public key is query param now
* AuthIsRequired error introduced
* Integration test fixed and improved
=> DEX-696 Address in WS API private streams

dex-it-common/src/main/scala/com/wavesplatform/dex/it/fp/FOps.scala, dex-it-common/src/main/scala/com/wavesplatform/dex/it/sttp/SttpBackendOps.scala, dex-it/src/test/scala/com/wavesplatform/it/sync/KafkaIssuesTestSuite.scala, dex/src/main/scala/com/wavesplatform/dex/AddressActor.scala, project/Dependencies.scala
* Reservable balances are freed in StoreFailed event handling (AddressActor)
* KafkaIssuesTestSuite integration test introduced
=> DEX-697 Free reserved balance after failed storing in queue

dex/src/main/scala/com/wavesplatform/dex/api/MatcherApiRoute.scala, dex/src/test/scala/com/wavesplatform/dex/api/MatcherApiRouteSpec.scala
* Matcher public key added to /matcher/settings endpoint
=> DEX-704 Matcher public key in settings

dex-it-common/src/main/scala/com/wavesplatform/dex/it/api/dex/DexApi.scala, dex-it-common/src/main/scala/com/wavesplatform/dex/it/api/dex/DexApiOps.scala, dex-it/src/test/scala/com/wavesplatform/it/sync/MatcherTestSuite.scala, dex/src/main/scala/com/wavesplatform/dex/api/MatcherApiRoute.scala
* Proxy requests will be rejected if their X-User-Public-Key token isn't match to public key/address from url param
* Integration tests added
=> DEX-707 Correct X-User-API-Key requirement

dex-it/src/test/scala/com/wavesplatform/it/sync/networking/DexClientFaultToleranceTestSuite.scala, dex/src/main/scala/com/wavesplatform/dex/SpendableBalancesActor.scala, dex/src/test/scala/com/wavesplatform/dex/SpendableBalancesActorSpecification.scala
* SpendableBalancesActor handles connection issues during spendable balance requests to Node
* Unit and integration tests added
=> DEX-706 Connection issues handling during balance requests

dex-it/src/test/scala/com/wavesplatform/it/sync/MultipleMatchersTestSuite.scala
* Dex 1 connected back to the network after disconnection in the first test
=> DEX-716 MultipleMatchersTestSuite fix

dex-it-common/src/main/scala/com/wavesplatform/dex/it/api/websockets/HasWebSockets.scala, dex-it/src/test/scala/com/wavesplatform/it/sync/KafkaIssuesTestSuite.scala, dex-it/src/test/scala/com/wavesplatform/it/sync/api/ws/WebSocketPrivateStreamTestSuite.scala, dex/src/main/scala/com/wavesplatform/dex/AddressActor.scala
* In case of event storing failure AddressActor notify about un-reservation and removes order from the active ones
* Method assertChanges moved to HasWebSockets
=> DEX-698 WS API notification about freed reserves

dex-it/src/test/scala/com/wavesplatform/it/sync/OrderHistoryTestSuite.scala, dex/src/main/scala/com/wavesplatform/dex/AddressActor.scala
* AddressActor uses v4 of OrderInfo of active orders
* Integration test improved
=> DEX-718 Correct average weighed price in REST API

dex-it/src/test/scala/com/wavesplatform/it/sync/KafkaIssuesTestSuite.scala, dex/src/main/scala/com/wavesplatform/dex/AddressActor.scala
* Removing from active orders in case of failure of the placements storing
* Do nothing in case of failure of the storing of cancels
=> DEX-725 Correct logic after storing into queue failure

dex-it/src/test/scala/com/wavesplatform/it/it.scala, dex-it/src/test/scala/com/wavesplatform/it/sync/MatcherRecoveryTestSuite.scala, dex/src/main/scala/com/wavesplatform/dex/AddressActor.scala, dex/src/main/scala/com/wavesplatform/dex/market/AggregatedOrderBookActor.scala, dex/src/main/scala/com/wavesplatform/dex/market/OrderBookActor.scala
* AddressActor handles OrderCancelFailed
* MatcherRecoveryTestSuite places orders then cancels some of them
=> DEX-674 MarketStatusRecoveryTestSuite stabilization

dex-it/src/test/scala/com/wavesplatform/it/sync/TradeBalanceAndRoundingTestSuite.scala
* test stabilized, the problem isn't fixed. Will be solved in DEX-734
=> DEX-732 TradeBalanceAndRoundingTestSuite stabilization

dex/src/main/scala/com/wavesplatform/dex/api/websockets/actors/WsHandlerActor.scala, dex/src/main/scala/com/wavesplatform/dex/market/AggregatedOrderBookActor.scala, dex/src/test/scala/com/wavesplatform/dex/api/websockets/WsHandlerActorSpec.scala
* WsHandlerActor:
- tracks order book and address subscriptions;
- sends success asset pair validation result to self then adds subscription;
- send unsubscribe request to all tracked addresses and order books before stop;
=> DEX-736 Cancel WS subscriptions after connection close

dex-it/src/test/scala/com/wavesplatform/it/sync/TradeBalanceAndRoundingTestSuite.scala, dex/src/main/scala/com/wavesplatform/dex/AddressActor.scala, dex/src/main/scala/com/wavesplatform/dex/db/OrderDB.scala, dex/src/main/scala/com/wavesplatform/dex/model/OrderBook.scala, dex/src/main/scala/com/wavesplatform/dex/queue/QueueEventWithMeta.scala, dex/src/test/scala/com/wavesplatform/dex/market/OrderBookActorSpecification.scala
* Restored a submitted order validation agains counter order's price;
* Added logs;
* Uncommented check it TradeBalanceAndRoundingTestSuite;
=> DEX-738 Additional logs and orderBook improvements

dex-it-common/src/main/scala/com/wavesplatform/dex/it/api/websockets/WsConnection.scala, dex-it/src/test/scala/com/wavesplatform/it/sync/api/ws/WsPingPongTestSuite.scala, dex/src/main/scala/com/wavesplatform/dex/Matcher.scala, dex/src/main/scala/com/wavesplatform/dex/api/MatcherWebSocketRoute.scala, dex/src/main/scala/com/wavesplatform/dex/api/websockets/actors/WsHandlerActor.scala
* serverSink recover errors of client messages parsing and forward InvalidJson error to sender
* Integration test improved
=> DEX-742 Handling of invalid client messages

dex-it/src/test/scala/com/wavesplatform/it/sync/api/ws/WsOrderBookStreamTestSuite.scala
* Everything is already worked since subscription request goes through MatcherActor runFor method
=> DEX-700 WS connection creation for not existed order book

dex-it/src/test/scala/com/wavesplatform/it/sync/api/ws/WsPingPongTestSuite.scala, dex/src/main/scala/com/wavesplatform/dex/api/websockets/connection/WsConnection.scala
* WsConnection got connectionLifetime field
* WsPingPongTestSuite was rewritten
=> DEX-753 WsPingPongTestSuite stabilization

dex-it-common/src/main/scala/com/wavesplatform/dex/it/dex/DexApi.scala, dex/src/main/scala/com/wavesplatform/dex/api/MatcherApiRoute.scala, dex/src/test/scala/com/wavesplatform/dex/api/MatcherApiRouteSpec.scala
* getOrderStatusInfoByIdWithSignature moved to orderbook segment
=> DEX-781 Orders info endpoint fix

dex-it-common/src/main/scala/com/wavesplatform/dex/it/waves/MkWavesEntities.scala, dex/src/main/scala/com/wavesplatform/dex/api/http/entities/MatcherResponse.scala, dex/src/main/scala/com/wavesplatform/dex/api/http/routes/MatcherApiRoute.scala, dex/src/main/scala/com/wavesplatform/dex/api/routes/PathMatchers.scala, dex/src/main/scala/com/wavesplatform/dex/error/MatcherError.scala, dex/src/test/scala/com/wavesplatform/dex/api/http/routes/MatcherApiRouteSpec.scala, waves-integration/src/main/scala/com/wavesplatform/dex/domain/account/Address.scala
* AddressPM changed signature, now its Either
* MatcherApiRoute got withCorrectAddress method
* New error InvalidAddress introduced
=> DEX-701 Address errors handling in REST API

dex-it/src/test/scala/com/wavesplatform/it/sync/MatcherTestSuite.scala, dex/src/main/scala/com/wavesplatform/dex/actors/address/AddressActor.scala, dex/src/main/scala/com/wavesplatform/dex/api/http/entities/HttpOrderBookHistoryItem.scala, dex/src/main/scala/com/wavesplatform/dex/model/OrderInfo.scala, dex/src/test/scala/com/wavesplatform/dex/api/http/entities/HttpOrderBookHistoryItemSpec.scala, dex/src/test/scala/com/wavesplatform/dex/api/http/routes/MatcherApiRouteSpec.scala, dex/src/test/scala/com/wavesplatform/dex/model/OrderInfoSpec.scala
* OrderInfo v5 introduced
* HttpOrderBookHistoryItem got version field
=> DEX-728 Order version in OrderInfo

dex-it/src/test/scala/com/wavesplatform/it/sync/api/ws/WsOrderBookStreamTestSuite.scala, dex/src/main/scala/com/wavesplatform/dex/api/ws/connection/TestWsHandlerActor.scala, dex/src/main/scala/com/wavesplatform/dex/api/ws/connection/WsConnection.scala, dex/src/main/scala/com/wavesplatform/dex/api/ws/state/WsOrderBookState.scala, dex/src/test/scala/com/wavesplatform/dex/api/http/routes/MatcherApiRouteSpec.scala
=> DEX-814 An accidentally removed subscription

dex-it/src/test/scala/com/wavesplatform/it/sync/api/ws/WsAddressStreamTestSuite.scala, dex/src/main/scala/com/wavesplatform/dex/AddressActor.scala, dex/src/main/scala/com/wavesplatform/dex/SpendableBalancesActor.scala, dex/src/test/scala/com/wavesplatform/dex/ActorsWebSocketInteractionsSpecification.scala
* Fixed a bug with invalid balances;
* Added logs of balance changes;
* Added a test to reproduce the issue.
=> DEX-827 Invalid balances

dex-it/src/test/scala/com/wavesplatform/it/sync/api/ws/WsAddressStreamTestSuite.scala, dex/src/main/scala/com/wavesplatform/dex/Matcher.scala, dex/src/main/scala/com/wavesplatform/dex/api/http/routes/MatcherApiRoute.scala, dex/src/main/scala/com/wavesplatform/dex/error/MatcherError.scala, dex/src/main/scala/com/wavesplatform/dex/model/OrderValidator.scala, dex/src/test/scala/com/wavesplatform/dex/model/OrderValidatorSpecification.scala, waves-ext/src/main/scala/com/wavesplatform/dex/grpc/integration/services/WavesBlockchainApiGrpcService.scala
=> DEX-828 Excess data in WS balance stream

dex/src/main/scala/com/wavesplatform/dex/actors/orderbook/AggregatedOrderBookActor.scala, dex/src/main/scala/com/wavesplatform/dex/api/ws/actors/WsInternalBroadcastActor.scala
WsInternalBroadcastActor 
* runSchedule after sending WS updates removed since there are no updates right after their sending
AggregatedOrderBookActor
* scheduling optimized. The main idea is: AOBA doesn't poll itself every 100ms for the accumulated updates if there are some subscriptions. Instead, after receiving command ApplyChanges it accumulates within 100ms all the changes and send them to subscriptions. That is only new ApplyChanges command schedules changes sending (if it wasn't scheduled by the previous ApplyChanges command)
=> DEX-815 AggregatedOrderBookActor scheduling optimization

dex-it/src/test/scala/com/wavesplatform/it/sync/MatcherTestSuite.scala, dex/src/main/scala/com/wavesplatform/dex/model/MatcherModel.scala
* Counter remaining nominator now accumulates executedWeighedPriceNominator
=> DEX-856 Average Weighed Price fix

build.Jenkinsfile, deploy.Jenkinsfile, dex-it/src/test/scala/com/wavesplatform/it/sync/MatcherTestSuite.scala, project/ItTestPlugin.scala, tests-kafka.Jenkinsfile, tests-multiple-versions.Jenkinsfile, tests-specified-versions.Jenkinsfile, tests.Jenkinsfile
=> DEX-890 Stucking builds

dex-jmh/src/test/scala/com/wavesplatform/dex/model/orderbook/OrderBookCancelBenchmark.scala, dex/src/main/scala/com/wavesplatform/dex/Matcher.scala, dex/src/main/scala/com/wavesplatform/dex/api/http/routes/MatcherApiRoute.scala, dex/src/main/scala/com/wavesplatform/dex/api/routes/AuthRoute.scala, project/Dependencies.scala
* Akka-HTTP version updated to 10.2.0
* Routes in MatcherApiRoute organized according to style guide
=> DEX-729 Update akka-http version to 10.2.0

dex-it/src/test/scala/com/wavesplatform/it/WsSuiteBase.scala, dex-it/src/test/scala/com/wavesplatform/it/sync/api/ws/WsPingPongBaseSuite.scala, dex-it/src/test/scala/com/wavesplatform/it/sync/api/ws/WsPingPongExternalTestSuite.scala, dex/src/main/scala/com/wavesplatform/dex/api/ws/connection/WsConnection.scala
* Test have been rewritten, now they are based on messages counting, not time measurements
=> DEX-887 Ping pong tests stabilization

dex/src/main/resources/application.conf, dex/src/main/scala/com/wavesplatform/dex/Application.scala, dex/src/main/scala/com/wavesplatform/dex/Matcher.scala, dex/src/main/scala/com/wavesplatform/dex/queue/KafkaMatcherQueue.scala, dex/src/main/scala/com/wavesplatform/dex/queue/LocalMatcherQueue.scala, dex/src/main/scala/com/wavesplatform/dex/queue/MatcherQueue.scala
* Moved all shutdown processes to coordinated hooks;
* Added NTP shutdown.
=> DEX-842 Coordinated Shutdown

dex-it-common/src/main/scala/com/wavesplatform/dex/it/api/websockets/WsMessageOps.scala, dex-it-common/src/main/scala/com/wavesplatform/dex/it/dex/DexApiOps.scala, dex-it/src/test/scala/com/wavesplatform/it/sync/MatcherTestSuite.scala, dex-it/src/test/scala/com/wavesplatform/it/sync/OrderHistoryTestSuite.scala, dex-it/src/test/scala/com/wavesplatform/it/sync/RoundingIssuesTestSuite.scala, dex-it/src/test/scala/com/wavesplatform/it/sync/api/ws/WsAddressStreamTestSuite.scala, dex-it/src/test/scala/com/wavesplatform/it/sync/api/ws/WsInternalStreamTestSuite.scala, dex/src/main/scala/com/wavesplatform/dex/actors/address/AddressActor.scala, dex/src/main/scala/com/wavesplatform/dex/api/http/entities/HttpOrderBookHistoryItem.scala, dex/src/main/scala/com/wavesplatform/dex/api/ws/entities/WsFullOrder.scala, dex/src/main/scala/com/wavesplatform/dex/api/ws/entities/WsOrder.scala, dex/src/main/scala/com/wavesplatform/dex/api/ws/state/WsAddressState.scala, dex/src/main/scala/com/wavesplatform/dex/model/MatcherModel.scala, dex/src/main/scala/com/wavesplatform/dex/model/OrderInfo.scala, dex/src/test/scala/com/wavesplatform/dex/api/http/entities/HttpOrderBookHistoryItemSpec.scala, dex/src/test/scala/com/wavesplatform/dex/api/http/routes/MatcherApiRouteSpec.scala, dex/src/test/scala/com/wavesplatform/dex/api/ws/ActorsWebSocketInteractionsSpecification.scala, dex/src/test/scala/com/wavesplatform/dex/model/OrderBookTestSuite.scala, dex/src/test/scala/com/wavesplatform/dex/model/OrderInfoSpec.scala
* Field totalExecutedAmountOfPriceAsset added to FillingInfo, OrderInfo (v6 implementation introduced), HttpOrderBookHistoryItem, WsOrder and WsFullOrder
* Unit and integration tests fixed
=> DEX-913 Executed Amount of Price Asset

dex-it-common/src/main/scala/com/wavesplatform/dex/it/api/websockets/HasWebSockets.scala, dex-it/src/test/scala/com/wavesplatform/it/sync/api/ws/WsConnectionTestSuite.scala, dex/src/main/scala/com/wavesplatform/dex/Matcher.scala, dex/src/main/scala/com/wavesplatform/dex/api/http/routes/MatcherApiRoute.scala, dex/src/main/scala/com/wavesplatform/dex/api/ws/actors/WsExternalClientDirectoryActor.scala, dex/src/main/scala/com/wavesplatform/dex/api/ws/actors/WsExternalClientHandlerActor.scala, dex/src/main/scala/com/wavesplatform/dex/api/ws/protocol/WsRatesUpdates.scala, dex/src/main/scala/com/wavesplatform/dex/api/ws/protocol/WsServerMessage.scala, dex/src/main/scala/com/wavesplatform/dex/api/ws/routes/MatcherWebSocketRoute.scala, dex/src/test/scala/com/wavesplatform/dex/api/http/routes/MatcherApiRouteSpec.scala, dex/src/test/scala/com/wavesplatform/dex/api/http/routes/MatcherWebSocketRouteSpec.scala, dex/src/test/scala/com/wavesplatform/dex/api/ws/WsMessagesSerdeSpecification.scala
* Rates snapshot is sent right after connection
* Rates updates handled
=> DEX-904 Rates updates in WS API

dex-it-common/src/main/scala/com/wavesplatform/dex/it/api/websockets/HasWebSockets.scala, dex-it/src/test/scala/com/wavesplatform/it/sync/api/ws/WsConnectionTestSuite.scala, dex-it/src/test/scala/com/wavesplatform/it/sync/api/ws/WsRatesUpdatesTestSuite.scala, dex/src/main/scala/com/wavesplatform/dex/Matcher.scala, dex/src/main/scala/com/wavesplatform/dex/api/ws/actors/WsExternalClientDirectoryActor.scala, dex/src/main/scala/com/wavesplatform/dex/api/ws/actors/WsExternalClientHandlerActor.scala, dex/src/main/scala/com/wavesplatform/dex/api/ws/protocol/WsAddressSubscribe.scala, dex/src/main/scala/com/wavesplatform/dex/api/ws/protocol/WsClientMessage.scala, dex/src/main/scala/com/wavesplatform/dex/api/ws/protocol/WsRatesUpdates.scala, dex/src/main/scala/com/wavesplatform/dex/api/ws/protocol/WsRatesUpdatesSubscribe.scala, dex/src/main/scala/com/wavesplatform/dex/api/ws/protocol/WsUnsubscribe.scala, dex/src/main/scala/com/wavesplatform/dex/api/ws/routes/MatcherWebSocketRoute.scala, dex/src/test/scala/com/wavesplatform/dex/api/http/routes/MatcherApiRouteSpec.scala, dex/src/test/scala/com/wavesplatform/dex/api/http/routes/MatcherWebSocketRouteSpec.scala, dex/src/test/scala/com/wavesplatform/dex/api/ws/actors/WsExternalClientHandlerActorSpec.scala
* Subscribe, unsubscribe
* Integration tests added
=> DEX-925 WS API Rates Updates subscription

.scalafmt.conf, dex-it-common/src/main/scala/com/wavesplatform/dex/it/api/websockets/HasWebSockets.scala, dex-it/src/test/scala/com/wavesplatform/it/sync/MultipleMatchersTestSuite.scala, dex-it/src/test/scala/com/wavesplatform/it/sync/api/ws/WsConnectionTestSuite.scala, dex-it/src/test/scala/com/wavesplatform/it/sync/api/ws/WsPingPongBaseSuite.scala, dex-it/src/test/scala/com/wavesplatform/it/sync/api/ws/WsPingPongExternalTestSuite.scala, dex-it/src/test/scala/com/wavesplatform/it/sync/api/ws/WsPingPongInternalTestSuite.scala, dex/src/main/scala/com/wavesplatform/dex/actors/AskActor.scala, dex/src/main/scala/com/wavesplatform/dex/api/http/entities/HttpWebSocketConnections.scala, dex/src/main/scala/com/wavesplatform/dex/api/ws/actors/WsExternalClientDirectoryActor.scala, dex/src/main/scala/com/wavesplatform/dex/api/ws/actors/WsExternalClientHandlerActor.scala, dex/src/main/scala/com/wavesplatform/dex/api/ws/connection/WsConnection.scala, dex/src/main/scala/com/wavesplatform/dex/api/ws/routes/MatcherWebSocketRoute.scala, dex/src/main/scala/com/wavesplatform/dex/fp/MapImplicits.scala, dex/src/test/scala/com/wavesplatform/dex/api/http/routes/MatcherWebSocketRouteSpec.scala
Also contains:
* A possible fix for invalid number of connections in GET /ws/v0/connections;
* Fixed rules of scalafmt.
=> DEX-929 WebSockets connections additional stats

dex/src/main/scala/com/wavesplatform/dex/api/http/routes/MatcherApiRoute.scala, dex/src/main/scala/com/wavesplatform/dex/error/MatcherError.scala, dex/src/test/scala/com/wavesplatform/dex/api/http/routes/MatcherApiRouteSpec.scala
* invalidJsonParsingRejectionsHandler fixed
* unit test added
=> DEX-675 Correct error for unsupported Content-Type

dex-jmh/src/test/scala/com/wavesplatform/dex/model/address/AddressActorStartingBenchmark.scala, dex-jmh/src/test/scala/com/wavesplatform/dex/model/orderbook/OrderBookAddBenchmark.scala, dex-jmh/src/test/scala/com/wavesplatform/dex/model/orderbook/OrderBookCancelBenchmark.scala, dex-jmh/src/test/scala/com/wavesplatform/dex/model/state/OrderBookBenchmarkState.scala, dex/src/test/scala/com/wavesplatform/dex/gen/OrderBookGen.scala
=> DEX-931 Benchmark for processing events during Matcher start

waves-ext/src/main/scala/com/wavesplatform/dex/grpc/integration/protobuf/GRPCErrors.scala, wavesNode.sbt
=> DEX-941 Prepare release 2.2.3

dex-it-common/src/main/scala/com/wavesplatform/dex/it/config/GenesisConfig.scala, dex-it-common/src/main/scala/com/wavesplatform/dex/it/config/PredefinedAssets.scala, dex-it-common/src/main/scala/com/wavesplatform/dex/it/dex/DexApi.scala, dex-it-common/src/main/scala/com/wavesplatform/dex/it/json/package.scala, dex-it-common/src/main/scala/com/wavesplatform/dex/it/waves/Implicits.scala, dex-it-common/src/main/scala/com/wavesplatform/dex/it/waves/MkWavesEntities.scala, dex-it/src/test/scala/com/wavesplatform/it/config/DexTestConfig.scala, dex-it/src/test/scala/com/wavesplatform/it/sync/MultipleMatchersTestSuite.scala, dex-it/src/test/scala/com/wavesplatform/it/sync/PostgresHistoryDatabaseTestSuite.scala, dex-it/src/test/scala/com/wavesplatform/it/sync/compat/DatabaseBackwardCompatTestSuite.scala, dex-it/src/test/scala/com/wavesplatform/it/sync/smartcontracts/ExtraFeeTestSuite.scala, dex-it/src/test/scala/com/wavesplatform/it/sync/smartcontracts/OrdersFromScriptedAccTestSuite.scala, dex-it/src/test/scala/com/wavesplatform/it/sync/smartcontracts/OrdersFromScriptedAssetTestSuite.scala, dex-it/src/test/scala/com/wavesplatform/it/sync/smartcontracts/ProofAndAssetPairTestSuite.scala, dex/src/main/resources/application.conf, dex/src/main/scala/com/wavesplatform/dex/Application.scala, dex/src/main/scala/com/wavesplatform/dex/actors/address/AddressActor.scala, dex/src/main/scala/com/wavesplatform/dex/settings/MatcherSettings.scala, dex/src/main/scala/com/wavesplatform/dex/settings/OrderHistorySettings.scala, dex/src/main/scala/com/wavesplatform/dex/settings/utils/ConfigOps.scala, waves-integration-it/src/test/scala/com/wavesplatform/dex/grpc/integration/clients/WavesBlockchainAsyncClientTestSuite.scala
Also:
* Fixed a bug: an order history initializes even we disabled it
* Bigger delay in DatabaseBackwardCompatTestSuite
=> Merge version-2.2.3 into master

dex-it-common/src/main/scala/com/wavesplatform/dex/it/cache/CachedData.scala, dex-it-common/src/main/scala/com/wavesplatform/dex/it/docker/BaseContainer.scala, dex-it/src/test/scala/com/wavesplatform/it/WsSuiteBase.scala
The right Diff for WsAddressChanges
=> DEX-958 Prepare release 2.2.4

waves-grpc/build.sbt, waves-integration/src/main/scala/com/wavesplatform/dex/grpc/integration/clients/CombinedWavesBlockchainClient.scala, waves-integration/src/main/scala/com/wavesplatform/dex/grpc/integration/clients/status/BlockchainStatus.scala, waves-integration/src/main/scala/com/wavesplatform/dex/grpc/integration/clients/status/StatusTransitions.scala, waves-integration/src/main/scala/com/wavesplatform/dex/grpc/integration/clients/status/StatusUpdate.scala, waves-integration/src/test/scala/com/wavesplatform/dex/grpc/integration/clients/status/StatusTransitionsTestSuite.scala
Removed a possibility of this case
=> DEX-1005 Hanging TransientResolving

dex/src/test/scala/com/wavesplatform/dex/actors/orderbook/AggregatedOrderBookActorSpec.scala, dex/src/test/scala/com/wavesplatform/dex/gen/OrderBookGen.scala
Replacing Gen.resize with sizeGen.flatMap
=> DEX-987 AggregatedOrderBookActorSpec fails

project/Dependencies.scala, waves-integration/src/main/scala/com/wavesplatform/dex/grpc/integration/clients/CombinedWavesBlockchainClient.scala, waves-integration/src/main/scala/com/wavesplatform/dex/grpc/integration/clients/domain/StatusTransitions.scala, waves-integration/src/main/scala/com/wavesplatform/dex/grpc/integration/clients/domain/WavesNodeEvent.scala, waves-integration/src/main/scala/com/wavesplatform/dex/grpc/integration/clients/domain/portfolio/DefaultPessimisticPortfolios.scala, waves-integration/src/main/scala/com/wavesplatform/dex/grpc/integration/clients/domain/portfolio/LookAheadPessimisticPortfolios.scala, waves-integration/src/main/scala/com/wavesplatform/dex/grpc/integration/clients/domain/portfolio/PessimisticPortfolios.scala, waves-integration/src/main/scala/com/wavesplatform/dex/grpc/integration/clients/matcherext/MatcherExtensionGrpcAsyncClient.scala, waves-integration/src/test/scala/com/wavesplatform/dex/grpc/integration/clients/domain/StatusTransitionsTestSuite.scala, waves-integration/src/test/scala/com/wavesplatform/dex/grpc/integration/clients/domain/portfolio/PessimisticPortfoliosTestSuiteBase.scala
Code:
* DefaultPessimisticPortfolios:
* addPending and processForged batching;
* an implementation of removeFailed;
* Updated a code to support of removing invalid transactions.
Dependencies: added alleycats-core.
=> DEX-1021 Removing of invalid transactions from PessimisticPortfolios

dex-it/src/test/scala/com/wavesplatform/it/matcher/api/http/cancel/CancelOrdersByAddressAndIdsSpec.scala, dex/src/main/scala/com/wavesplatform/dex/grpc/integration/clients/MatcherExtensionAssetsWatchingClient.scala, project/Dependencies.scala, waves-ext/src/main/scala/com/wavesplatform/dex/grpc/integration/services/WavesBlockchainApiGrpcService.scala, waves-integration/src/main/scala/com/wavesplatform/dex/domain/utils/ScorexLogging.scala, waves-integration/src/main/scala/com/wavesplatform/dex/grpc/integration/clients/blockchainupdates/GrpcBlockchainUpdatesControlledStream.scala, waves-integration/src/main/scala/com/wavesplatform/dex/grpc/integration/clients/combined/CombinedStream.scala, waves-integration/src/main/scala/com/wavesplatform/dex/grpc/integration/clients/combined/CombinedWavesBlockchainClient.scala, waves-integration/src/main/scala/com/wavesplatform/dex/grpc/integration/clients/matcherext/GrpcUtxEventsControlledStream.scala, waves-integration/src/main/scala/com/wavesplatform/dex/grpc/integration/clients/matcherext/UtxEventConversions.scala, waves-integration/src/test/scala/com/wavesplatform/dex/grpc/integration/clients/combined/CombinedStreamTestSuite.scala
* Introduced a state machine for CombinedStream;
* Fixed multiple bugs;
* Added an additional logging.
=> DEX-1035 Better algorithm for CombinedStream

dex/src/main/scala/com/wavesplatform/dex/actors/SpendableBalancesActor.scala, dex/src/main/scala/com/wavesplatform/dex/actors/address/AddressActor.scala, dex/src/main/scala/com/wavesplatform/dex/grpc/integration/clients/MatcherExtensionAssetsWatchingClient.scala, dex/src/main/scala/com/wavesplatform/dex/tool/connectors/DexExtensionGrpcConnector.scala, dex/src/test/scala/com/wavesplatform/dex/actors/SpendableBalancesActorSpecification.scala, dex/src/test/scala/com/wavesplatform/dex/actors/address/AddressActorSpecification.scala, dex/src/test/scala/com/wavesplatform/dex/api/ws/ActorsWebSocketInteractionsSpecification.scala, dex/src/test/scala/com/wavesplatform/dex/matching/ReservedBalanceSpecification.scala, dex/src/test/scala/com/wavesplatform/dex/model/OrderHistoryStub.scala, waves-ext/src/main/scala/com/wavesplatform/dex/grpc/integration/services/WavesBlockchainApiGrpcService.scala, waves-grpc/src/main/protobuf/waves_blockchain_api.proto, waves-integration-it/src/test/scala/com/wavesplatform/dex/grpc/integration/clients/WavesBlockchainAsyncClientTestSuite.scala, waves-integration/src/main/scala/com/wavesplatform/dex/grpc/integration/clients/WavesBlockchainClient.scala, waves-integration/src/main/scala/com/wavesplatform/dex/grpc/integration/clients/combined/CombinedWavesBlockchainClient.scala, waves-integration/src/main/scala/com/wavesplatform/dex/grpc/integration/clients/matcherext/MatcherExtensionCachingClient.scala, waves-integration/src/main/scala/com/wavesplatform/dex/grpc/integration/clients/matcherext/MatcherExtensionClient.scala, waves-integration/src/main/scala/com/wavesplatform/dex/grpc/integration/clients/matcherext/MatcherExtensionGrpcAsyncClient.scala
Spendable balances are stored locally, also Matcher replies immediately on second and further WS subscriptions.
=> DEX-1039 AddressActor spendable balances optimization

dex-it/src/test/scala/com/wavesplatform/it/matcher/bugs/Dex1052BugSpec.scala, dex/src/main/resources/application.conf, dex/src/main/scala/com/wavesplatform/dex/tool/connectors/DexExtensionGrpcConnector.scala, dex/src/test/scala/com/wavesplatform/dex/settings/BaseSettingsSpecification.scala, dex/src/test/scala/com/wavesplatform/dex/settings/MatcherSettingsSpecification.scala, waves-integration-it/src/test/scala/com/wavesplatform/dex/grpc/integration/clients/WavesBlockchainClientTestSuite.scala, waves-integration/src/main/scala/com/wavesplatform/dex/grpc/integration/clients/combined/CombinedWavesBlockchainClient.scala
* Added new setting: waves.dex.waves-blockchain-client.combined-client-settings.max-cached-latest-block-updates;
* Added a new integration test.
=> DEX-1052 Wrong balances test

dex-it-common/src/main/scala/com/wavesplatform/dex/it/api/dex/AsyncEnrichedDexApi.scala, dex-it/src/test/scala/com/wavesplatform/it/WsSuiteBase.scala, dex/src/main/resources/application.conf, dex/src/main/scala/com/wavesplatform/dex/actors/events/OrderEventsCoordinatorActor.scala, dex/src/main/scala/com/wavesplatform/dex/actors/orderbook/AggregatedOrderBookActor.scala, dex/src/main/scala/com/wavesplatform/dex/actors/tx/ExchangeTransactionBroadcastActor.scala, dex/src/main/scala/com/wavesplatform/dex/api/ws/state/WsOrderBookState.scala, dex/src/main/scala/com/wavesplatform/dex/model/package.scala, dex/src/test/scala/com/wavesplatform/dex/actors/tx/ExchangeTransactionBroadcastActorSpecification.scala, docs/order-auto-canceling.md, waves-integration/src/main/scala/com/wavesplatform/dex/collections/FifoSet.scala, waves-integration/src/main/scala/com/wavesplatform/dex/grpc/integration/clients/domain/portfolio/LookAheadPessimisticPortfolios.scala
* ExchangeTransactionBroadcastActor - fixed an issue with retrying and notifications;
* OrderEventsCoordinatorActor - fixed an invalid handling of ApplyObservedByBroadcaster.
=> DEX-1064 Check and clarify a transaction observation process

dex-it/src/test/scala/com/wavesplatform/it/sync/BouncingBalancesTestSuite.scala, waves-integration/src/main/scala/com/wavesplatform/dex/grpc/integration/clients/domain/StatusTransitions.scala, waves-integration/src/main/scala/com/wavesplatform/dex/grpc/integration/clients/domain/WavesFork.scala, waves-integration/src/test/scala/com/wavesplatform/dex/grpc/integration/clients/domain/StatusTransitionsTestSuite.scala, waves-integration/src/test/scala/com/wavesplatform/dex/grpc/integration/clients/domain/WavesForkTestSuite.scala
See StatusTransitions for more information.
=> DEX-1099 Tradable balance issues during rollbacks

waves-integration/src/main/scala/com/wavesplatform/dex/grpc/integration/clients/combined/CombinedStream.scala, waves-integration/src/test/scala/com/wavesplatform/dex/grpc/integration/clients/combined/CombinedStreamTestSuite.scala
* Fixed the issue;
* Back-ported status of stream from master in order to stabilize CombinedStreamTestSuite.
=> DEX-1132 CombinedStream doesn't start

dex-it-common/src/main/scala/com/wavesplatform/dex/it/docker/BaseContainer.scala
Logging format:
```
13:08:34.872 INFO  [1-thread-1] c.w.d.i.d.DexContainer - Started container; Exposed ports for networks [waves-1865344633]: 6886 -> 55018/tcp; 10001 -> 55017/tcp
.....
Connected container to network; Exposed ports for networks [waves-1865344633]: 6871 -> 55021/tcp; 6887 -> 55019/tcp; 6870 -> 55022/tcp; 6869 -> 55023/tcp; 6868 -> 55024/tcp; 6881 -> 55020/tcp; 6863 -> 55025/tcp; 6862 -> 55026/tcp
```
=> DEX-1161 log docker ports

dex-it-common/src/main/scala/com/wavesplatform/dex/it/api/BaseContainersKit.scala, dex-it-common/src/main/scala/com/wavesplatform/dex/it/api/dex/HasDex.scala, dex-it-common/src/main/scala/com/wavesplatform/dex/it/api/node/HasWavesNode.scala, dex-it-common/src/main/scala/com/wavesplatform/dex/it/docker/BaseContainer.scala, dex-it-common/src/main/scala/com/wavesplatform/dex/it/docker/DexContainer.scala, dex-it-common/src/main/scala/com/wavesplatform/dex/it/docker/WavesNodeContainer.scala, dex-it/src/test/resources/dex-servers/logback-container.xml, dex-it/src/test/resources/logback-test.xml, dex-it/src/test/scala/com/wavesplatform/it/sync/networking/MultipleMatchersOrderCancelTestSuite.scala, dex-ws-load/src/test/resources/logback.xml, dex/src/main/scala/com/wavesplatform/dex/time/NTP.scala, dex/src/main/scala/kamon/instrumentation/logback/tools/CompactSpanIDConverter.scala, dex/src/main/scala/kamon/instrumentation/logback/tools/CompactTraceIDConverter.scala
* Fixed logging issues with PARSER_ERROR;
* Rewriting MultipleMatchersOrderCancelTestSuite.
=> DEX-1344 Prepare release 2.3.5

dex/src/main/resources/application.conf, dex/src/main/scala/com/wavesplatform/dex/cli/WavesDexCli.scala, dex/src/main/scala/com/wavesplatform/dex/settings/CliSettings.scala
args-overrides ->  default-args
=> DEX-1344 Prepare release 2.3.5 - CLI fixes

dex/src/main/resources/application.conf, dex/src/main/scala/com/wavesplatform/dex/actors/events/OrderEventsCoordinatorActor.scala, dex/src/test/scala/com/wavesplatform/dex/actors/events/OrderEventsCoordinatorActorSpec.scala, waves-integration/src/main/scala/com/wavesplatform/dex/collections/FifoSet.scala, waves-integration/src/main/scala/com/wavesplatform/dex/grpc/integration/clients/domain/portfolio/LookAheadPessimisticPortfolios.scala, waves-integration/src/test/scala/com/wavesplatform/dex/grpc/integration/clients/domain/portfolio/LookAheadPessimisticPortfoliosTestSuite.scala
…ing, processConfirmed and addPending case
=> DEX-1606 fix stuck in utx transactions
